patternfly/patternfly-elements

package-lock.json, package.json
pull in [this generator-rhelement fix](https://github.com/RHElements/generator-rhelement/pull/3)
=> update generator-rhelement, fixes #4

elements/rh-button/README.md, elements/rh-card/README.md, elements/rh-cta/README.md, elements/rh-datetime/README.md, elements/rh-dropdown-button/README.md, elements/rh-dropdown-menu/README.md, elements/rh-dropdown/README.md, elements/rh-icon-panel/README.md, elements/rh-icon/README.md, elements/rh-multiswitch/README.md, elements/rh-number/README.md, elements/rh-overpass/README.md, elements/rh-search-result/README.md, elements/rhelement/README.md, elements/rhelement/package.json, package-lock.json
=> remove polyserve

elements/rh-cta/rh-cta.story.js
How do you add more than one set of knobs?
=> Add knobs for CTA priority

.gitattributes
No more merge conflicts or noisy diffs for compiled files!
=> apply binary merge resolution to all compiled files

package-lock.json, package.json
Removing generator-rhelement and pointing to generator-pfelement.
=> pointing to generator-pfelement

elements/pfe-accordion/demo/index.html, elements/pfe-accordion/package-lock.json, elements/pfe-accordion/src/pfe-accordion-header.scss, elements/pfe-sass/extends/_extends.scss
* linked to extends in accordion scss file
* set extends naming to expand button
=> Added CSS extends

package-lock.json, package.json, scripts/leftover-check.sh
This PR adds a script that is run every time a branch is checked out.  The script looks for any elements which were created in another branch but do not exist in the current branch.
I think this scenario has happened to all of us.
- look at `elements/`
- see some element you created a month ago and abandoned
- wonder *WHY IS THAT STILL HERE?!*
The reason element directories stay around is that within them is a node_modules directory that is not tracked by git.  When you `git checkout my-branch`, it will delete any files that aren't in `my-branch`.  The catch is that it only deletes tracked files.  Untracked files are totally unknown by git and it refuses to delete files you didn't tell it to pay attention to.
This PR will resolve that issue by notifying you of any leftover elements. …
=> on branch checkout, look for leftover elements from other branches

elements/pfe-accordion/demo/index.html, elements/pfe-accordion/package-lock.json, elements/pfe-accordion/package.json, elements/pfe-accordion/src/pfe-accordion.js, elements/pfe-accordion/test/pfe-accordion_test.html
Adding a mutation observer so the component will continue working properly if new headers and panels are added.
Fixes #332
=> adding a mutationobserver to pfe-accordion

elements/pfe-sass/mixins/_mixins.scss, elements/pfe-sass/variables/_colors.scss
* changed the accordion button border from pfe-var-surface--border--lightest to pfe-var-surface--border
* fixed the expanded accordion heavy border var: pfe-var--surface--border-width--heavy. Was missing extra hyphen.
=> PFE-accordion border fixes

.storybook/config.js, .storybook/test-theme.css, elements/pfe-markdown/demo/index.html, elements/pfe-markdown/demo/pfe-markdown.story.js, elements/pfe-markdown/src/pfe-markdown.js, elements/pfe-markdown/src/pfe-markdown.json, elements/pfe-markdown/src/pfe-markdown.scss, elements/pfelement/src/pfelement.js
@kylebuch8 I created a fork that adds a schema, updates the storybook file to use it, and adds support for the context variables which can influence the text color if the markdown appears on a dark background.
=> PFE Markdown fork | Adds schema and storybook utils to demo

elements/pfe-accordion/package-lock.json, elements/pfe-accordion/src/pfe-accordion.js
=> moving this.button initialization to the constructor

elements/pfe-health-index/src/pfe-health-index.js
=> fixing the super call in the constructor of pfe-health-index

elements/pfe-accordion/gulpfile.js, elements/pfe-autocomplete/gulpfile.js, elements/pfe-avatar/gulpfile.js, elements/pfe-band/gulpfile.js, elements/pfe-card/gulpfile.js, elements/pfe-content-set/gulpfile.js, elements/pfe-cta/gulpfile.js, elements/pfe-datetime/gulpfile.js, elements/pfe-health-index/gulpfile.js, elements/pfe-icon-panel/gulpfile.js, elements/pfe-icon/gulpfile.js, elements/pfe-markdown/gulpfile.js, elements/pfe-number/gulpfile.js, elements/pfe-page-status/gulpfile.js, elements/pfe-tabs/gulpfile.js, elements/pfelement/gulpfile.js, elements/pfelement/src/pfelement.js, scripts/gulpfile.factory.js
Reads the version in the package.json file and adds it as a getter during the build process
Fixes #428
=> adding a version getter to each component

elements/pfe-sass/variables/_maps.scss
Fixes #476
* Updated pfe-sass to include animation-speed which will drive the animation in pfe-accordion and soon pfe-collapsible.
=> adding global variable animation-speed

CHANGELOG-prerelease.md, package-lock.json, package.json
---
Adding @patternfly/patternfly as a dependency of this project so that styles can be easily imported into components.
This just adds the dependency but doesn't actually import any styles into components.
=> Add Patternfly as a dependency

elements/pfe-card/src/pfe-card.html, elements/pfe-card/src/pfe-card.scss, elements/pfe-card/test/pfe-card_test.html, examples/index.html, package-lock.json
Proposed additions to the Card alignment branch via @markcaron!
=> pfe-card CTA alignment fork

elements/pfe-progress-indicator/README.md, elements/pfe-progress-indicator/demo/index.html, elements/pfe-progress-indicator/demo/pfe-progress-indicator.story.js, elements/pfe-progress-indicator/src/pfe-progress-indicator.json, elements/pfe-progress-indicator/src/pfe-progress-indicator.scss
* Link to discovery documentation (should contain all the planning and requirements for this work):
- See the `DISCOVERY.md` template at the root of the project
---
*
1. 
=> added sm md and xl sizes for progress indicator

CHANGELOG-prerelease.md, elements/pfe-card/demo/pfe-card.story.js
=> fix: updating pfe-card story so Image overflow works

CHANGELOG-prerelease.md, elements/pfe-content-set/src/pfe-content-set.js
Not having this causes the code to get in an infinite loop
=> fix: wrapping the observer reconnect in a setTimeout

docs/content/develop/templates.md, docs/content/theme/_index.md, docs/content/theme/pfe-theme-slots.md, elements/pfe-band/demo/index.html
* Link to discovery documentation (should contain all the planning and requirements for this work):
- See the `DISCOVERY.md` template at the root of the project
---
* Updated band demo and some md files to have the prefix `pfe` on the CTA's priority so they will render correctly. 
1. 
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.co …
=> update markup to pfe- prefix

elements/pfe-accordion/demo/index.html, elements/pfe-navigation/demo/it-index.html, elements/pfe-navigation/demo/ja-index.html, elements/pfe-navigation/src/_shared-assets.scss, elements/pfe-navigation/src/pfe-navigation--lightdom.scss, elements/pfe-navigation/src/pfe-navigation-item.scss, elements/pfe-navigation/src/pfe-navigation.scss, elements/pfe-sass/functions/_general.scss, examples/index.html
Still needs some adjustments for Edge
=> WIP Adjusted widths & flex props of various nav items

CHANGELOG-prerelease.md, elements/pfe-cta/src/pfe-cta.scss
* Remove scope from CTA so broadcast vars apply to CTAs with or without priority attribute to resolve [issue 658](https://github.com/patternfly/patternfly-elements/issues/658)
1. Created a container on the CTA demo page like this <div style="background:#000;--theme:dark" > and it should go from looking like this:
to this:
=> Update pfe-cta to include broadcast vars all the time (issue #658)

CHANGELOG-prerelease.md, LICENSE.txt, elements/pfe-accordion/LICENSE.txt, elements/pfe-autocomplete/LICENSE.txt, elements/pfe-avatar/LICENSE.txt, elements/pfe-badge/LICENSE.txt, elements/pfe-band/LICENSE.txt, elements/pfe-card/LICENSE.txt, elements/pfe-collapse/LICENSE.txt, elements/pfe-content-set/LICENSE.txt, elements/pfe-cta/LICENSE.txt, elements/pfe-datetime/LICENSE.txt, elements/pfe-health-index/LICENSE.txt, elements/pfe-icon-panel/LICENSE.txt, elements/pfe-icon/LICENSE.txt, elements/pfe-markdown/LICENSE.txt, elements/pfe-modal/LICENSE.txt, elements/pfe-navigation/LICENSE.txt, elements/pfe-number/LICENSE.txt, elements/pfe-page-status/LICENSE.txt, elements/pfe-progress-indicator/LICENSE.txt, elements/pfe-sass/LICENSE.txt, elements/pfe-select/LICENSE.txt, elements/pfe-styles/LICENSE.txt, elements/pfe-tabs/LICENSE.txt, elements/pfe-toast/LICENSE.txt, elements/pfelement/LICENSE.txt
=> [chore] Update license date from 2019 to 2020

examples/index.html, examples/wrapper.html, scripts/doc-listing-inject.js
* Update examples wrapper template and script to add newlines to the file making diffs easier to read
---
1. Preview the `examples/index.html` and ensure the components are separated by newlines
=> chore: Add newlines to the example file to make diffs easier to read

elements/pfe-navigation/README.md, elements/pfe-navigation/demo/index.html, elements/pfe-navigation/demo/pfe-navigation.story.js
=> docs: fixing the icons in pfe-navigation

elements/pfe-collapse/demo/pfe-collapse.story.js
=> docs: switching pfe-collapse story from heading tag to button

README.md, docs/content/develop/step-1a.md
Update readme & Docs with clearer labels on shell commands #721
=> docs: Update docs for shell commands

CHANGELOG-prerelease.md
Changelog was incorrect & missing some entries.
=> Fix changelog

.prettierignore
Currently prettier isn't running on commit based on how many PRs are coming in with unprettified code.  Updating the prettierignore file to hopefully get it running again.
=> fix prettier on commit

.travis.yml, scripts/doc-listing-inject.js, scripts/gulpfile.factory.js, scripts/rollup.config.factory.js, spandx.config.js
=> chore: Prettier updates

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
* Removed the repeated title from the top of the template
* Clarified the infrastructure checklist as separate from the browser checklist
* Clarified the Ready-for-merge checklist, updated them to statements rather than questions
=> docs: PR template updates

CHANGELOG-prerelease.md, elements/pfe-select/demo/index.html, elements/pfe-select/demo/pfe-select.story.js, elements/pfe-select/src/pfe-select.js, elements/pfelement/src/pfelement.js
* Issue #758 - update pfe-select to use event emission
1. Should pass automated test cases.
=> feat: Update pfe-select to use new event emission format (#758)

CHANGELOG-prerelease.md, examples/index.html, generators/element/templates/src/element.js
* Update generator JS file to convert slot names to camel case
1. Run the generator using `npm run new`
2. Add at least 2 slots, `message-on, color` (one with a dash and one without)
3. Check the generated element to ensure the JS has converted the slot name with a dash in it into camel case
=> fix: issue with slots containing dashes in JS file

CHANGELOG-prerelease.md, docs/content/getting-started/_index.md
- ADDED STORYBOOK LINK!
- Also added notes about adding to dependencies & including javascript
=> Update getting started docs

docs/content/develop/step-2c.md
fixing broken link at the bottom of this page:
https://patternfly.github.io/patternfly-elements/develop/step-2c/
=> fix doc link

CHANGELOG-prerelease.md, elements/pfe-navigation/src/pfe-navigation-item.js
=> fix: pfe-navigtation-item shouldn't add duplicative event listeners

CHANGELOG-prerelease.md, elements/pfe-card/demo/pfe-card.story.js, elements/pfe-card/src/pfe-card.html, elements/pfe-card/src/pfe-card.scss, elements/pfe-card/test/pfe-card_test.html, package-lock.json
Fixes #860
- Navigate to the [`pfe-card` demo page](https://deploy-preview-861--happy-galileo-ea79c4.netlify.app/elements/pfe-card/demo/)
- Open the developer tools
- Drop in the following code into the console and execute it
```
const card = document.createElement("pfe-card");
card.textContent = "Test Card";
document.body.appendChild(card);
```
- Make sure the card is visible at the bottom of the page
- Add the following code into the console and execute it
```
const header = document.createElement("h2");
header.setAttribute("slot", "pfe-card--header");
header.textContent = "Card Header";
card.prepend(header);
```
- Validate that the new header shows up in the card.
**Browser testing**
- Tested in Firefox, Safari, Chrome, Edge 80+, Edge 18, and IE11
=> fix: pfe-card header and footer slot issues

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_component.md, .github/PULL_REQUEST_TEMPLATE/new_component.md, .github/PULL_REQUEST_TEMPLATE/update_component.md, .github/PULL_REQUEST_TEMPLATE/update_documentation.md, .github/PULL_REQUEST_TEMPLATE/update_infrastructure.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md
* Added more Issue and PR templates
* Added code of conduct
* Added contribution guidelines
=> docs: Update templates and guides

.github/ISSUE_TEMPLATE/update_component.md
Create a new issue template for updating an existing component
=> Updating an existing component template

elements/pfe-number/demo/pfe-number.story.js
Fixes #633
- Run storybook locally: `npm run storybook`
- Validate that the Storybook demo looks like this
=> docs: pfe-number update for storybook

.github/labeler.yml, CHANGELOG-prerelease.md
- Add a label for when generator files are updated
- Add the tools label when the .github folder is updated
=> feat: Update labeler to label generator changes

elements/pfe-navigation/demo/index.html, elements/pfe-navigation/src/pfe-navigation.scss, examples/index.html, package-lock.json, test/index.html
---
name: pfe-nav mega menu tray and single column dropdown
labels: "feature"
---
Added mega menu tray styles and pfe-cta examples in mega menu tray. Added single column dropdown class and example of single col dropdown menu.
@wesruv you can remove this line from the `index.html` `"../../pfe-dropdown/dist/pfe-dropdown.umd.js"` I just had that there to review the pfe-dropdown on the page.
=> Cpfed 3735 megamenu tray

CHANGELOG-prerelease.md
Changelog updates for the prerelease 54 tag
=> Prerelease 54 changelog

elements/pfe-navigation/demo/index.html, elements/pfe-navigation/src/pfe-navigation.scss
---
name: CPFED 3780 single col styles - separator and groups
labels: "needs code review"
---
Added styles and demo for groups and separator feature inside of single column dropdown. Updated some styles based on feedback from pfe-icons PR CPFED-3779.
1. Open the "Solutions" menu item
2. Open the "Learning & Support" menu item
=> Cpfed 3780 single col styles

.github/workflows/automerge.yml, .github/workflows/visualtests.yml
Wrong version of the browserstack plugin in the script 🤦
=> fix: fix issue in new automerge scripts

elements/pfe-navigation/src/pfe-navigation.html, elements/pfe-navigation/src/pfe-navigation.js
Made search dropdown a wrapper div instead of the slot, so aria-hidden would never get applied to the slot
---
name: Default template
about: Generic template
labels: "feature, needs: AT updates, needs: changelog, needs: branch testing, priority: low"
---
- (#100) Description
- [Link](https://5e6089f7c8e38b0008963801--happy-galileo-ea79c4.netlify.com/examples/) 
Link to discovery documentation (should contain all the planning and requirements for this work):
- 
1. 
Please **squash** when merging and ensure your commit message uses [conventional …
=> fix: CPFED-3846: Fixing an issue where search form became invisible

elements/pfe-navigation/src/pfe-navigation.scss
---
name: Default template
about: Generic template
labels: "feature, needs: AT updates, needs: changelog, needs: branch testing, priority: low"
---
- (#100) Description
- [Link](https://5e6089f7c8e38b0008963801--happy-galileo-ea79c4.netlify.com/examples/) 
Link to discovery documentation (should contain all the planning and requirements for this work):
- 
1.  …
=> fix: Need to remove button spacing when grid is present

.github/workflows/automerge.yml, .github/workflows/label.yml, .github/workflows/tests.yml
Updating the automerge logic:
- This action is now triggered at the completion of the `Build & test` job
- If logic checks for:
* Review state = approved _AND_
* Check suite (required tests) completed & passed _AND_
* (PR does not have labels: on hold, work in progress _OR_
* PR opened by dependabot)
1. Automerge job should run after the Build & test job
2. Automerge job should not merge if the above criteria are not met 
- [] Repository compiles and tests pass.
Please **squash** when merging and ensure your commit message uses …
=> chore: Update automerge logic

.github/workflows/automerge.yml, .github/workflows/label.yml, .github/workflows/project.yml, .github/workflows/tests.yml, package-lock.json
- Prettify the UI by adding clearer labels and descriptions
- Separate labelling steps into distinct jobs so they run concurrently
=> chore: Add pretty labels to clarify actions view in UI

elements/pfe-navigation/src/_variables-mixins.scss, elements/pfe-navigation/src/pfe-navigation--lightdom.scss, elements/pfe-navigation/src/pfe-navigation.js, elements/pfe-navigation/src/pfe-navigation.scss
* Fixed font that was incorrect on buttons
* Simplified logo focus state and omitted hover
* Fixed issue where icons weren't centered
* Adjusted down arrow on desktop items with dropdowns
* Switched alt-focus to use pseudo element to prevent rendering issues and jumpiness
=> CPFED-3884: Misc design updates from UX team

CHANGELOG-1.x.md
=> docs: update 1.0 changelog

elements/pfe-navigation/demo/single-nav-sticky-alert-banner.html
---
name: CPFED-3949: add alert banner demo and remove role banner from pfe-nav
---
add alert banner demo and remove role banner from pfe-nav and wrap both in a header tag
1. Start the project with npm
2. Navigation to the single-nav-sticky-alert-banner.html file in the browser.
=> CPFED-3949: add alert banner demo and remove role banner from pfe-nav

.github/workflows/automerge.yml, .github/workflows/label.yml, .github/workflows/tests.yml
- Attempt to fix the workflow_dispatch event in the Build & test
- Add `dependabot-preview` user to the if logic for running visual regression tests
- Use merge instead of rebase for the automerge action
- Remove if logic to automerge action (the script respects restrictions set on the branch)
- Add automerge attempt if the pull request is approved
Once the PR is approved, see if the automerge action is triggered by checking the "Checks" tab.
Should also show up here:
https://github.com/patternfly/patternfly-elements/actions?query=branch%3Achore-automerge-updates+workflow%3A%22Auto-merge+pull+request+if+requirements+met%22
Can only validate the workflow run updates after the merge because they have to exist on the main branch:
- Go here and try to click the `Run workflow` button: …
=> CI: Clean up issues still in the scripts

LICENSE.txt, elements/pfe-accordion/LICENSE.txt, elements/pfe-autocomplete/LICENSE.txt, elements/pfe-avatar/LICENSE.txt, elements/pfe-badge/LICENSE.txt, elements/pfe-band/LICENSE.txt, elements/pfe-button/LICENSE.txt, elements/pfe-card/LICENSE.txt, elements/pfe-collapse/LICENSE.txt, elements/pfe-content-set/LICENSE.txt, elements/pfe-cta/LICENSE.txt, elements/pfe-datetime/LICENSE.txt, elements/pfe-dropdown/LICENSE.txt, elements/pfe-health-index/LICENSE.txt, elements/pfe-icon-panel/LICENSE.txt, elements/pfe-icon/LICENSE.txt, elements/pfe-jump-links/LICENSE.txt, elements/pfe-markdown/LICENSE.txt, elements/pfe-modal/LICENSE.txt, elements/pfe-navigation/LICENSE.txt, elements/pfe-number/LICENSE.txt, elements/pfe-page-status/LICENSE.txt, elements/pfe-progress-indicator/LICENSE.txt, elements/pfe-select/LICENSE.txt, elements/pfe-styles/LICENSE.txt, elements/pfe-tabs/LICENSE.txt, elements/pfe-toast/LICENSE.txt, elements/pfelement/LICENSE.txt, generators/element/templates/LICENSE.txt
=> docs: Bump licenses

package.json
Added a minimum and maximum node version supported by the project to the package.json.
**Needs nvm installed.**
1. `nvm install 8 && nvm use 8`
2. `npm rebuild && npm run build`
3. Should fail to rebuild with build errors
1. `nvm install 13 && nvm use 13`
2. `npm rebuild && npm run build`
3. Should fail to rebuild with build errors
1. `nvm install 10 && nvm use 10`
2. `npm rebuild && npm run build`
3. Should succeed
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contri …
=> chore: add engines package json

elements/pfe-navigation/demo/index.html, elements/pfe-navigation/demo/index_react.html, elements/pfe-navigation/demo/index_vue.html, elements/pfe-navigation/demo/single-nav-sticky-alert-banner.html, elements/pfe-navigation/demo/single-nav-sticky.html, elements/pfe-navigation/demo/single-nav.html, elements/pfe-navigation/demo/variations.html, elements/pfe-navigation/mock/site-switcher.html, elements/pfe-navigation/src/pfe-navigation.html, elements/pfe-navigation/src/pfe-navigation.js, elements/pfe-navigation/src/pfe-navigation.scss
---
name: Cpfed 4025 create new pr with a11y updates from stale PR
---
Redid a11y updates from this [PR](https://github.com/patternfly/patternfly-elements/pull/1236) onto a fresh branch to avoid lots of merge conflicts with the epic branch since it was updated with the code from master before that PR was merged.
=> Cpfed 4025 create new pr

CHANGELOG-1.x.md
Update the changelog with the latest release deets
=> chore: Update changelog

.gitattributes, .gitconfig, package-lock.json, package.json
Package-lock files are difficult diffs to resolve.  [npm-merge-driver](https://www.npmjs.com/package/npm-merge-driver) attempts to solve this by providing a better tool for resolving these conflicts.  This branch adds this package to the project and sets up the necessary configuration for it to do its thing.
1. Pull in an update from the main branch that includes a package-lock.json change.
=> tools: Attempt to resolve package-lock merge conflicts more seamlessly

package-lock.json, package.json, scripts/build.sh
=> chore: Patch build script

elements/pfe-navigation/src/pfe-navigation.html, elements/pfe-navigation/src/pfe-navigation.js
@wesruv first PR for i18n work. Currently supporting all languages listed on rhdc. 
**Couple notes:**
- I was using rhdc's translations but it looks like they aren't translating "menu" so we still need that one
- need to discuss language slot (not a blocker for this PR)
=> Cpfed 3933 i18n

CHANGELOG-1.x.md, elements/pfe-accordion/src/_shared-assets.scss, elements/pfe-sass/functions/_custom-properties.scss, elements/pfe-sass/mixins/_custom-properties.scss, elements/pfe-sass/variables/_1-definitions.scss
We want pfe-sass to be usable outside of the PFE project as a utility but the use of the $repo variable causes naming issues for pfe-var, pfe-typography, and pfe-content because it means any external repo extending this will end up with a new variable name (`--rh-theme--foo` vs. `--pfe-theme--foo`) which might not be desired.  To prevent this issue, we're adding an additional sass variable, $custom-prop-prefix (try conflicting with that name!), which maps to the `$repo` variable but can be overwritten.  This allows other projects to maintain `--pfe-theme` in the variable naming but remap the `$repo` variable to their own project names.
- (#100) Description of issue
- [Link](https://deploy-preview-<pr_number>--happy-galileo-ea79c4.ne …
=> feat: Adding $custom-prop-prefix to resolve naming conflicts

elements/pfe-accordion/src/_shared-assets.scss
A comment was deleted on accident!
=> chore: Minor comment ressurection

elements/pfe-accordion/package.json, elements/pfe-autocomplete/package.json, elements/pfe-avatar/package.json, elements/pfe-badge/package.json, elements/pfe-band/package.json, elements/pfe-button/package.json, elements/pfe-card/package.json, elements/pfe-clipboard/package.json, elements/pfe-codeblock/package.json, elements/pfe-cta/package.json, elements/pfe-dropdown/package.json, elements/pfe-health-index/package.json, elements/pfe-icon-panel/package.json, elements/pfe-icon/package.json, elements/pfe-jump-links/package.json, elements/pfe-markdown/package.json, elements/pfe-modal/package.json, elements/pfe-page-status/package.json, elements/pfe-progress-indicator/package.json, elements/pfe-select/package.json, elements/pfe-tabs/package.json, elements/pfe-toast/package.json
- pfe-sass needs to be listed in the dependency tree (not as a devDependency) in order for lerna to be run in parallel.
1. Compile a component like pfe-card.
2. Validate that pfe-sass compiles first.
=> chore: Update dependency tree

docs/content/develop/step-5.md, docs/content/getting-started/_index.md, docs/content/theme/_index.md, docs/layouts/_default/list.html, docs/layouts/_default/single.html, docs/layouts/partials/header.html
Update prerelease references to 1.x
=> docs: Update version references

elements/pfe-accordion/src/pfe-accordion.js, elements/pfe-content-set/demo/index.html, elements/pfe-content-set/src/pfe-content-set.html, elements/pfe-content-set/src/pfe-content-set.js, elements/pfe-content-set/src/pfe-content-set.scss, elements/pfe-tabs/src/pfe-tab.js
- (#100) Description of issue
- [Link](https://deploy-preview-<pr_number>--happy-galileo-ea79c4.netlify.app//examples/) 
- 
1. 
=> Migrating content set to use dynamic slot

.eleventy.js
JSDoc creates nested folders with CSS and JS assets necessary to render the preview page.  Need to update 11ty to bring in folders AND files via passthrough.
Preview: https://608b1523d8927a00076570f6--patternfly-elements.netlify.app/elements/pfelement/demo/
=> chore: add missing JSDoc assets for 11ty

elements/pfe-navigation-account/demo/fake-wes-auth.js, elements/pfe-navigation-account/package-lock.json, elements/pfe-navigation-account/package.json, elements/pfe-navigation-account/src/pfe-navigation-account.html, elements/pfe-navigation-account/src/pfe-navigation-account.js, elements/pfe-navigation/demo/access.html, elements/pfe-navigation/demo/catalog.html, elements/pfe-navigation/demo/connect.html, elements/pfe-navigation/demo/index.html, elements/pfe-navigation/package-lock.json, elements/pfe-navigation/package.json, elements/pfe-navigation/src/ie-polyfills.js, elements/pfe-navigation/src/pfe-navigation--lightdom.scss, elements/pfe-navigation/src/pfe-navigation.html, elements/pfe-navigation/src/pfe-navigation.js, elements/pfe-navigation/src/pfe-navigation.scss, elements/pfe-navigation/src/sass-includes/_variables-mixins.scss
@kelsS @TylerMartin5 FYI, this is a bunch of changes that include:
* integrating the site switcher
* making the 'slide over' on expand at mobile (that all red hat has) generic so other things could use it
* IE11 fixes
* a11y updates based on changes we've had in the last few weeks
=> Cpfed 3689 mega update

package-lock.json, package.json
=> chore: Bump yo version

.storybook/config.js
Moving the knobs panel to the bottom because the content is so dense now.
=> chore: Update location of the knobs panel

elements/pfe-badge/package.json
Wrong filename in the package for pfe-badge (points to pfe-accordion). From [PatternFly forum](https://forum.patternfly.org/t/issue-with-a-patternfly-elemnt-but-i-can-not-create-one/446) via [jogibear9988](https://forum.patternfly.org/u/jogibear9988).
=> chore: Update pfe-badge package.json path 

elements/pfe-navigation/demo/index.html, elements/pfe-navigation/demo/single-nav-sticky.html
Added lang attribute to html tag of the demos to address lighthouse issue.
=> CPFED-4210: add lang to html tags to fix a11y issue on lighthouse

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/new_component.md, .github/ISSUE_TEMPLATE/update_component.md, .github/PULL_REQUEST_TEMPLATE/new_component.md, .github/PULL_REQUEST_TEMPLATE/update_component.md, .github/PULL_REQUEST_TEMPLATE/update_documentation.md, .github/PULL_REQUEST_TEMPLATE/update_infrastructure.md
Updated the issue and PR templates to reflect changes in how GitHub displays issue #s and the new Netlify link being added as a comment.
Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.  Documentation updates do not require a CHANGELOG entry.
=> chore: Updating a few templates with GitHub changes

.github/workflows/project.yml, .github/workflows/workflow.yml
As the project boards have been split out into prioritization (issues) and workflow (PRs), I updated the automatic processing to use the new headings and board URLs.
=> chore: Support updated project boards

.github/workflows/project.yml, .github/workflows/workflow.yml
Archive issues & PRs when they are closed
=> chore: Add a step to archive issues/PRs when closed

.github/workflows/tests.yml
=> chore: Update AT to capture PR number from branch

CHANGELOG-1.x.md, elements/pfe-tabs/src/pfe-tab.scss
- (#1086) Vertically align tab text
- [Link](https://deploy-preview-1737--patternfly-elements.netlify.app/components/tabs/) 
- `pfe-tab.scss` changed to make tab content flex and take up 100% of containter height.
1. Go to [`/components/tabs`](https://deploy-preview-1737--patternfly-elements.netlify.app/components/tabs/) on the demo site
2. Change the outerHTML of a horizontal tabs element to something with lots of text, preferably with a nautical or showtunes theme, like this:
```html
<pfe-tabs tab-align="center" aria-orientation="horizontal" variant="wind" role="tablist" pfelement="" class="PFElement" type="combo" has_tab="" has_panel="" selected-index="0" on="light">
<pfe-tab role="tab" slot="tab" aria-selected="true" …
```
=> feat: vertically center pfe-tab content

CHANGELOG-1.x.md, elements/pfe-badge/package.json, elements/pfe-modal/package.json
Fixing some typos in the package.json files of pfe-badge and pfe-modal. We discovered them when trying to import the dependencies in our app. 
pfe-badge: https://codesandbox.io/s/reverent-chaum-i5fl7?file=/src/App.js
pfe-modal: https://codesandbox.io/s/great-almeida-gpfe8?file=/src/App.js
=> fix: typos in package.json files

CHANGELOG-1.x.md, elements/pfe-primary-detail/src/pfe-primary-detail.js
Safari had an issue that showed up on scroll due to some bad code in a mutation observer callback, see #1758 
Escape key should have closed panel on compact view mode and did not, found the issue and addressed it
Removed `.replace()` call which caused some errors in IE11
- [Link](https://deploy-preview-1761--patternfly-elements.netlify.app/elements/pfe-primary-detail/demo/) 
1. In Mobile Safari, go to a small screen width so the component is in compact mode
2. Click an item in the list to put the component in active state
3. Scroll down
4. Content should still be visible in component
1. In any browser, go to compact view mode
2. Click an item in the list to put the component in active state
3. Press escape
4. Component should be …
=> fix: #1756 #1758 Fix IE11 issues, Safari issues, and Esc key working on compact layout

CHANGELOG-1.x.md, elements/pfe-sass/mixins/_containers.scss
Fixes regression in the accent border mixin shared by accordion and jump-links.
- #1788 
- Added px value defaults to `@mixin accent-bar()` offset.  Without them, height and width calc() are invalid CSS.
1. Go here
2. Do this
=> fix: added px value defaults for accent-bar mixin

elements/pfe-jump-links/pfe-jump-links-nav.ts, elements/pfe-jump-links/pfe-jump-links-panel.ts, elements/pfe-jump-links/test/pfe-jump-links.spec.ts
Updated jump-links based on your suggestions in the previous PR.  Thanks Benny 👍
=> feat(jump-links) 2.0 Add new ComposedEvent to jump-links

.github/dependabot.yml
Maybe someone other than me should be assigned to review dependabot...
=> chore: update reviewers for dependabot

CHANGELOG-1.x.md, docs/_includes/_foot.html, docs/index.html
Removes Storybook links in PFE website footer.
- #1843 
- [Link](https://deploy-preview-1844--happy-galileo-ea79c4.netlify.app/examples/) 
1. [Go here](https://deploy-preview-1844--patternfly-elements.netlify.app/)
2. Verify that there is no storybook link in the footer.
3. Navigate to one of the component pages.
=> chore: remove Storybook links for homepage and footer include

elements/pfe-dropdown/demo/pfe-dropdown.js, elements/pfe-dropdown/docs/index.md, elements/pfe-dropdown/package.json, elements/pfe-dropdown/pfe-dropdown-item.scss, elements/pfe-dropdown/pfe-dropdown-item.ts, elements/pfe-dropdown/pfe-dropdown.ts, elements/pfe-dropdown/test/pfe-dropdown.spec.ts
- update docs
- added `expanded` public property
- fixed keyboard navigation issues
- added tests for keyboard navigation
=> feat: Pfe tools/pfe dropdown

elements/pfe-autocomplete/pfe-autocomplete.ts, elements/pfe-autocomplete/pfe-search-droplist.ts, elements/pfe-autocomplete/test/pfe-autocomplete.spec.ts, patches/@custom-elements-manifest+analyzer+0.5.7.patch
- Added tests
- Tweaked some of the events documentation
=> Pfe tools/pfe autocomplete

elements/pfe-jump-links/pfe-jump-links-nav.scss
- (#100) Description of issue
- 
1. Go here
2. Do this
1. Go here
2. Do this
=> fix(pfe-jump-links): aligning type to 1rem/16px

core/pfe-styles/demo/colors.html, core/pfe-styles/demo/pfe-styles.html, core/pfe-styles/demo/theme-test.html, core/pfe-styles/demo/typography-deprecated.html, core/pfe-styles/demo/typography-mobile.html, core/pfe-styles/demo/typography-px-not-rem.html, docs/framework-integration/react.md, docs/framework-integration/vue.md, docs/get-started/index.md, docs/kitchen-sink-deprecated.njk, docs/layout/index.md, docs/main.css, docs/quick-start/index.md, docs/red-hat-theme.css, docs/theming/colors.md, elements/pfe-cta/demo/pfe-cta.html, elements/pfe-cta/package.json
pfe-styles look good.  Just some minor updates to demos and docs. 👍
=> Pfe tools/pfe styles

elements/pfe-primary-detail/demo/demo.css, elements/pfe-primary-detail/demo/pfe-primary-detail.html, elements/pfe-primary-detail/demo/pfe-primary-detail.js, elements/pfe-primary-detail/package.json, elements/pfe-primary-detail/pfe-primary-detail.scss, elements/pfe-primary-detail/pfe-primary-detail.ts, elements/pfe-primary-detail/test/pfe-primary-detail.spec.ts
- `breakpoint` property moved from a 'read-only' public property to a private state property.  We felt this was an internal state instead of a property to be changed on the component.  The previous property was marked read-only in comments but it wasn't actually a read-only property and could be set externally.
- `active` property no longer is set by initialization to show the first nav item.  Instead, the first nav item is shown but active remains null until a user or programmatic interaction occurs.
- promises added to light dom upgrade methods to ensure they are completed resulting in smooth animations. 
- CSS style changes to reflect changes to the no longer exposed `breakpoint` property.  In its place, a  new `.compact` class is now added to the shadow dom when the breakpoint changes …
=> fix(primary detail): fix animations, move breakpoint prop to private

.changeset/nervous-sheep-walk.md, tools/create-element/generator/element.ts, tools/create-element/tsconfig.json, tools/pfe-tools/esbuild-plugins/package-version.ts
Fixes some compiler errors in create-element
=> fix build for `npm init @patternfly/element`

.github/workflows/release.yml, .lighthouserc.yml
see commit log
Please **rebase** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.
=> Release workflow using `npm i`,   lighthouse ci config

.changeset/tasty-dragons-drum.md, .github/workflows/release.yml, .gitignore, docs/_plugins/bundle.cjs, tools/pfe-tools/dev-server.ts, tools/pfe-tools/esbuild.ts
- bundle pfe.min.js and attach to releases
- npm pack each releases package and attach the tarball
Please **rebase** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.
=> feat(ci): release artifacts

.changeset/empty-cougars-remain.md, .changeset/soft-radios-hear.md, core/pfe-sass/mixins/_mixins.scss, elements/pfe-select/pfe-select.scss
Closes #1801
- [Link](https://deploy-preview-1907--patternfly-elements.netlify.app/components/select/demo/) 
- remove `pfe-arrow` mixin from pfe-sass, which was used only in pfe-select
- restore chevron to pfe-select
- set pointer-events on the chevron to none
1. browse to demo
2. note that chevron appears in menu
3. click on chevron with mouse
4. menu should open
Please **rebase** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.
=> fix(select): restore and fix chevron

.changeset/shiny-dots-rescue.md, elements/pfe-label/README.md, elements/pfe-label/custom-elements-manifest.config.js, elements/pfe-label/demo/demo.css, elements/pfe-label/demo/pfe-label.html, elements/pfe-label/demo/pfe-label.js, elements/pfe-label/docs/index.md, elements/pfe-label/package.json, elements/pfe-label/pfe-label.scss, elements/pfe-label/pfe-label.ts, elements/pfe-label/test/pfe-label.e2e.spec.ts, elements/pfe-label/test/pfe-label.spec.ts, elements/pfe-label/tsconfig.json, tsconfig.settings.json
Adds pfe-label component
1. `npm use`
2. `npm ci`
3. `npm run test`
=> feat(label): add pfe-label component

core/pfe-core/core.ts, docs/_includes/_head.njk
Docs pages: Reveal the body when components update
Fixes #1886
=> docs: autoreveal the body on docs pages

.changeset/twenty-parrots-smile.md, tools/create-element/package.json
*actually* ship all js code in create
=> fix(create): ship generator javascript

.changeset/gorgeous-knives-lick.md, tools/pfe-tools/package.json
ensures 11ty plugins are added to npm tarball
=> tools: publish 11ty plugins

.changeset/gold-taxis-grow.md, tools/pfe-tools/dev-server.ts
Fixes passing options to `nunjucksSPAMiddleware(_options)` for demo configuraiton.
When configuring the demo dev server, you would add the following configuration to `web-dev-server.config.js`.  However, this configuration would not load correctly as all the options weren't being passed to `nunjucksSPAMiddleware`.  This change fixes that so the options get passed through.
```
import { pfeDevServerConfig } from '@patternfly/pfe-tools/dev-server.js';
export default pfeDevServerConfig({
site: {
title: "Red Hat Design System",
logoUrl: "/docs/assets/red-hat.svg",
githubUrl: "https://github.com/RedHat-UX/red-hat-design-system",
description: "Red Hat Design System"
}
});
```
- Add the above `site` json to `web-dev-server.config.js` and restart the demo server with `npm start` the title and …
=> fix(tools): corrects passing options to demo config

.changeset/rotten-ties-thank.md, tools/pfe-tools/dev-server.ts
pass the user's options to the pfe dev server plugin
=> fix(tools): pass options to dev server

scripts/bundle-release.cjs
Exclude `pfe.min.tgz` from the glob of files used to generate said
Fixes https://github.com/patternfly/patternfly-elements/runs/6748649983?check_suite_focus=true
=> chore: fix bundle gh action script

.changeset/warm-fishes-listen.md, elements/pfe-jump-links/pfe-jump-links-nav.ts
- fix a predicate that updates light dom in jump links
- thereby fix #2079
=> fix(jump-links): shouldUpdateLightDOM

.changeset/dull-shoes-begin.md, tools/pfe-tools/package.json
Include the demo template file in the npm tarball
=> fix(tools): template file in tarball

.changeset/rude-pillows-pay.md, elements/pfe-tooltip/BaseTooltip.scss, elements/pfe-tooltip/README.md, elements/pfe-tooltip/pfe-tooltip.ts
Small updates, cleaning up some typos in the documentation for pfe-tooltip and fixing an scss variable that was incorrect in pfe-tooltip.
=> [pfe-tooltip] - Updating documentation, fixing scss variable

package-lock.json, package.json
Install netlify-plugin-github-actions from npm
=> chore: install netlify build plugin

.changeset/stupid-buttons-shop.md, elements/pfe-spinner/package.json
Added BaseSpinner.js to exports in package.json, so it can be imported in other repos
=> fix(spinner): add BaseSpinner.js to exports

package.json
build the icon sets during site build
should hopefully fix netlify site builds https://app.netlify.com/sites/patternfly-elements/deploys/634ec7e3997bd70008f7a2f3
=> chore: fix netlify site build

.changeset/khaki-pens-prove.md, elements/pfe-label/BaseLabel.scss, elements/pfe-label/BaseLabel.ts, elements/pfe-label/package.json, elements/pfe-label/pfe-label.scss, elements/pfe-label/pfe-label.ts
1. Moved base styles to pfe, as these aren't exported causing issue downstream.
1. `npm start` or view deploy preview
CSS didn't change just combined into the pfe-label.scss file.  But just in case look for any possible discrepancies.
=> fix(label): move base styles to pfe

CONTRIBUTING.md
(#2203) Quick start README link
=> docs: updates README quick start docs link

.changeset/clean-seals-unite.md, elements/pfe-tabs/package.json
Fixed package.json exports to include BaseTab, BaseTabPanel, PfeTab, PfeTabPanel
=> fix(tabs): fix package.json exports

.changeset/heavy-poems-greet.md, elements/pfe-tabs/BaseTabs.ts, elements/pfe-tabs/demo/pfe-tabs.js, elements/pfe-tabs/pfe-tabs.scss
- Added inset as a decorated property 
- Exports InsetVariant type
=> fix(tabs): export inset type and add inset as property

elements/pfe-label/BaseLabel.scss, elements/pfe-label/BaseLabel.ts, elements/pfe-label/pfe-label.scss, elements/pfe-label/pfe-label.ts, elements/pfe-label/test/pfe-label.spec.ts
- Abstracted base class property fields
- Removed reflected properties in `pfe-tabs.ts` opting for classMap() usage
=> refactor(label): abstract base class fields

.changeset/tender-beans-repair.md
Add changeset for changes done to pfe-label in https://github.com/patternfly/patternfly-elements/pull/2265  which was accidentally merged before changeset was added
=> docs(label): add changeset

.changeset/good-impalas-battle.md, .changeset/red-trainers-sniff.md, elements/pfe-timestamp/pfe-timestamp.ts, elements/pfe-tooltip/BaseTooltip.ts, package-lock.json, tools/create-element/main.ts
- Placate TypeScript in create cli's main entrypoint
- Update the package-lock
Should unblock #2267
=> fix(create): typescript error

tsconfig.settings.json
Enable es2022 language features (for `array.at`)
Should unblock #2267
=> chore: enable array.at in tsconfig

.changeset/wicked-clouds-count.md, elements/pfe-tabs/pfe-tab-panel.ts, elements/pfe-tabs/pfe-tab.ts, elements/pfe-tabs/test/pfe-tabs.spec.ts, package-lock.json, tools/create-element/generator/element.ts, tools/eslint-config/package.json
- Update eslint-config's dependencies
- lint some files (accordion files will be handled in #2266)
=> chore(eslint-config): update dependencies

elements/pfe-card/test/pfe-card.spec.ts
skip and comment out the flaky a11ySnapshot test for card. We should revisit this later, but for now it's just a time sink.
This block release so please merge ASAP
=> test(card): fix test file

elements/pf-avatar/BaseAvatar.ts, elements/pf-avatar/test/pf-avatar.spec.ts
- Fixed `pf-avatar` typescript build errors.  Added more type checking.
=> fix(avatar): typescript build errors

elements/pf-button/demo/form-control.js, elements/pf-button/demo/pf-button.js, elements/pf-jump-links/demo/pf-jump-links.js, elements/pf-jump-links/demo/scrollspy-with-subsections.js, elements/pf-progress-stepper/demo/pf-progress-stepper.js, elements/pf-tabs/README.md, elements/pf-tabs/demo/pf-tabs.js
Added the element internals polyfill to all component demos that use it.
=> docs: add element internals polyfill to component demos 

docs/index.html
- add global footer to main page
=> docs: add footer to main page

.changeset/tools-analyzer-demos.md, tools/pfe-tools/custom-elements-manifest/demos.ts
1. find demos in both pfe and rhds repos
1. analyze here and in rhds - manifest should include demos references
=> fix(tools): find demos

.changeset/tools-dev-server-demo-exports.md, tools/pfe-tools/dev-server/index.html, tools/pfe-tools/package.json
1. fix the demo page import and it's associated export map
2. replace remaining `--pfe` styles
1. run dev server here
2. link pfe tools and run dev server in rhds
=> fix(tools): fix demo script import and styles

.changeset/silent-penguins-kneel.md, elements/package.json
1. add generated icons to package exports
=> fix(icon): add icon package exports

.changeset/smooth-eyes-thank.md, package-lock.json, tools/pfe-tools/package.json
=> chore(tools): update 11ty

elements/pf-avatar/BaseAvatar.ts, elements/pf-avatar/demo/pf-avatar.html
1. Added dark variant avatar for pf-avatar.
2. Added demo in the pf-avatar HTML file. 
fixes - https://github.com/patternfly/patternfly-elements/issues/2324
=> feat(avatar): add dark variant image

docs/home.css, docs/index.html
1. Updated the home.css to address the mobile issues in the header on the homepage
1. Visit the homepage
1. Look at how amazing it looks now
Fixes #2385
=> docs: fixing the mobile view on the homepage

.changeset/chilly-pens-marry.md, package-lock.json, tools/pfe-tools/dev-server/config.ts, tools/pfe-tools/package.json
Fixes #2387 
1. update the version of web-dev-server-plugin-lit-css, after https://github.com/bennypowers/lit-css/pull/35
2. refactor the config file
1. run the dev server, change some element css files
=> fix(tools): bust element css browser cache

.changeset/giant-trainers-jam.md, .changeset/perfect-fishes-study.md, core/pfe-core/controllers/internals-controller.ts, tools/pfe-tools/test/a11y-snapshot.ts
1. added `labels` and `validity` getters and `setFormValue`, `setValidity`, `checkValidity` and `reportValidity` methods to `InternalsController`
1. make a (silly) FACE and use the new features
1. Will help for rh-audio-player's controls
=> feat(core): internals controller form features

.changeset/pf-switch-2372.md, elements/pf-switch/pf-switch.ts
1. Updated docs for pf-switch element 
fixes - https://github.com/patternfly/patternfly-elements/issues/2372
=> docs: added change event for switch element

.changeset/pf-panel-2402.md, docs/main.css, elements/pf-panel/docs/pf-panel.md, elements/pf-panel/pf-panel.css
1. Fixed raised and bordered variants CSS styles
2. Improved pf-panel docs to more closely match PFv4
fixes - https://github.com/patternfly/patternfly-elements/issues/2402
=> fix(panel): raised and bordered variants

.changeset/base-tab-id.md, elements/pf-tabs/BaseTab.ts, elements/pf-tabs/BaseTabPanel.ts, elements/pf-tabs/pf-tab-panel.ts, elements/pf-tabs/pf-tab.ts
1. move the random ID code from PfTab/PfTabPanel to BaseTab/BaseTabPanel
1. run test
1. alternative to https://github.com/RedHat-UX/red-hat-design-system/pull/954
=> fix(tabs): assign random id in BaseTab/Panel

.changeset/strong-donkeys-care.md, tools/pfe-tools/dev-server/config.ts, web-dev-server.config.js
1. Fixed `*-lightdom.css` support in dev server config
2. Adds pfeDevServerConfig for lightdom.css support in this repo
1. Launch local dev server, add a `*-lightdom.css` file to any component, link that file in a demo, CSS should load.
=> fix(tools): dev server config for lightdom css

.github/workflows/preview.yml
Here's a workflow run to debug the current CI failure.
=> chore: debug CI in preview.yml

.changeset/core-floating-ui-ts-error.md, core/pfe-core/controllers/floating-dom-controller.ts
1. fix the import from floating ui
=> fix(core): typescript import from floating-ui library

.changeset/slot-controller-react.md, core/pfe-core/controllers/slot-controller.ts
1. ensure that slot controller components render correctly when used in react
1.
1. fixes the workaround in https://codesandbox.io/p/sandbox/pfe-react-wrappers-3g6x6r?file=%2Fsrc%2FApp.tsx%3A8%2C1-13%2C1
=> fix(core): slot controller when used in react

.changeset/react-dts.md, elements/tsconfig.json, package-lock.json, tools/pfe-tools/react/generate-wrappers.ts
1. generate .d.ts for react wrappers
2. bump versions in package lock so that `npm i @patternfly/elements` gets the new hotness
=> fix: generate d.ts for react wrappers

.changeset/tabs-expand-cem.md, .changeset/tabs-expand-event.md, docs/components/components.md, elements/pf-button/docs/pf-button.md, elements/pf-popover/docs/pf-popover.md, elements/pf-tabs/BaseTab.ts, elements/pf-tabs/docs/pf-tabs.md, elements/pf-tabs/pf-tab.ts, elements/pf-tabs/pf-tabs.ts, eleventy.config.cjs
=> docs(button): examples of onclick

.changeset/late-actors-give.md, .changeset/neat-colts-jam.md, .changeset/pf-card-heading-specificity.md
1. Formatted changesets to follow guidelines as mentioned in https://github.com/patternfly/patternfly-elements/pull/2546
1.
1.
=> chore(docs): format changesets

.github/workflows/preview.yml
1. fix the netlify preview deploy step
1. does this pr deploy a PR preview?
=> chore: fix netlify deploy command

.changeset/logger-debug.md, .changeset/slot-logger.md, core/pfe-core/controllers/logger.ts, core/pfe-core/controllers/slot-controller.ts
1. moves debug logs from SlotController to debug
Technically breaking but NBD IMO
=> fix(core): logger.debug, info

.changeset/tidy-numbers-rush.md
1.  Fixed changeset formatting
1.
1.
=> chore: fix changeset formatting

elements/pf-tabs/test/pf-tabs.spec.ts
1. Fixed tabs tests
Closes #2683
1.
1.
=> test(tabs): lint

tools/pfe-tools/dev-server/demo.css, tools/pfe-tools/dev-server/plugins/pfe-dev-server.ts
1. make sure dev server loads typescript sources
2. make sure dev server body fills screen height
=> fix(tools): dev server load ts sources

tools/pfe-tools/dev-server/plugins/pfe-dev-server.ts
1. more whoopsies from the dev server
=> fix(tools): load ts sources from core

elements/pf-back-to-top/README.md
=> docs(back-to-top): update README.md

elements/pf-dropdown/pf-dropdown.css, elements/pf-dropdown/pf-dropdown.ts
1. apply dropdown menu styles to slotted menu
1. try the versions dropdown on the dp https://deploy-preview-2713--patternfly-elements.netlify.app/components
=> fix(dropdown): styles for slotted menu

docs/_includes/layout-blog.njk, docs/blog/pfe-3-release.md
1. Drafted release notes for pfe-3
https://deploy-preview-2735--patternfly-elements.netlify.app/blog/pfe-3-release/
=> docs: 3.0 release notes

.changeset/eleven-llamas-follow.md, elements/pf-select/README.md, elements/pf-select/demo/checkbox-input-no-badge.html, elements/pf-select/demo/checkbox-input.html, elements/pf-select/demo/grouped-checkbox-input.html, elements/pf-select/demo/grouped-single.html, elements/pf-select/demo/pf-select.html, elements/pf-select/demo/single-with-description.html, elements/pf-select/docs/pf-select.md, elements/pf-select/pf-select.ts, elements/pf-select/test/pf-select.spec.ts
1. ensure placeholder value is used for button label unless there is a selected item
1. add placeholder attr
2. see that it is used as button text
3. select an item
4. see that the item's value is used as button text
1. is the use of the placeholder as a disabled item correct?
=> fix(select): placeholder button text

.changeset/odd-months-flow.md, tools/pfe-tools/dev-server/plugins/pfe-dev-server.ts
=> fix(tools): redirect dev server for lightdom css

.changeset/purple-boxes-stare.md, elements/package.json, elements/pf-back-to-top/pf-back-to-top.css
1. Fixed the background color change on back-to-top button, on hover and focus.
1.  Confirm that the color are correct.
1. Check the token values.
=> fix(back-to-top): hover color

elements/pf-text-area/docs/pf-text-area.md
1. Added documentation for the text-area usage
1. npm run start 
2. load the documentation  localhost:8080
3. verify that documentation usage has been updated
=> docs(text-area): usage documentation

elements/package.json, elements/pf-text-input/docs/pf-text-input.md
1. Added usage for pf-text-input element
1. Check if the usage of pf-text-input correct or not.
=> docs(text-input): usage documentation

.changeset/little-bags-post.md, elements/pf-select/pf-select.ts, elements/pf-select/test/pf-select.spec.ts
1. fix bug which corrupted pf-select state when it was nested in shadow roots
1. check unit tests
=> fix(select): change event deep shadow

.changeset/mighty-pigs-check.md, .github/workflows/tests.yml, package.json, scripts/bundle.js, tools/pfe-tools/custom-elements-manifest/demos.ts, tools/pfe-tools/custom-elements-manifest/lib/Manifest.ts, tools/pfe-tools/dev-server/plugins/import-map-generator.ts, tools/pfe-tools/package.json
1. Added fixes to resolve Windows OS compatibility issues.
1. The code should run in all three OS( Windows, Linux, Mac).
1. Please run this code on local and check if its working.
=> fix(tools): windows compatibility

tools/pfe-tools/custom-elements-manifest/custom-elements-manifest.ts
1. Corrected import of `Manifest.js`
1.
1.
=> fix(tools): correct import of manifest

.changeset/loud-rings-lay.md, elements/pf-icon/pf-icon.ts
1. Fixed lazy loading not properly calling correct load method
1.
1.
=> fix(icon): fix lazy loading 

core/pfe-core/package.json, core/pfe-core/ssr-shims.ts
1. make dom shims it's own file, importable from downstream packages
=> fix(core): improved ssr

.changeset/ready-garlics-lose.md, core/pfe-core/controllers/tabs-aria-controller.ts
1. avoid browser globals/apis in tabs aria controller
=> fix(core): tabs aria ssr compat

elements/pf-select/docs/pf-select.md
1. Added typehead usage document for pf-select
1. See if the usage documentation is added or not
=> [docs]2861: added typehead usage doc for pf-select

.changeset/beige-worlds-begin.md, .changeset/config.json, package-lock.json, tools/pfe-tools/package.json
1. update the version of changesets to the latest version
2. disable prettier in the changesets config
=> fix(tools): update changesets version

package-lock.json, tools/pfe-tools/package.json
1. bump changesets cli to fix [fatal error](https://github.com/patternfly/patternfly-elements/actions/runs/13392464424/job/37403199631)
=> fix(tools): bump changesets

.changeset/sixty-horses-appear.md, tools/pfe-tools/dev-server/plugins/import-map-generator.ts
1. pass important options to import map generator plugin
=> fix(tools): pass ignore option to generator plugin
