test/index.html

This change was added by accident. We need to remove it for our tests to pass.

removing rh-avatar test from test/index.html

---

elements/rh-layouts/demo/index.html
elements/rh-layouts/rh-layouts.css
elements/rh-layouts/rh-layouts.scss
elements/rh-layouts/rh-layouts.story.js
elements/rh-layouts/sass/_bullseye.scss
elements/rh-layouts/sass/_grid.scss
package.json

Adding bullseye back and fixing the grid gutters

---

README.md

@kylebuch8 i checked out the latest from master and while it's better, it still doesn't say you need to run `npm start` at the root *at the same time* that you need to run `npm run dev` within the component. I think it's important to explicitly state that the `npm start` needs to run the server continuously while doing active development. 
Here you go. :)

Suggested updates to documentation

---

spandx.config.js

There are about 86,000 files in node_modules. We need to tell Browsersync to stop watching these files. This dramatically speeds up page load times and gets rid of the Javascript head error that some of us were seeing in the command line.

ignoring node_modules

---

elements/rhelement/package.json

rhelement.js had an `npm start` script which no other elements have, and it was missing `npm run dev`.  This PR fixes that and makes it consistent with other elements.

make rhelement npm scripts identical to other elements

---

.gitattributes

This flags `elements/*/*.umd.js` files as binary, so that git diff doesn't do a text diff on them (it just says "this file changed"), and git merge just accepts the newer version without trying to do a text merge.
Ideally this would be done on every generated file (ie, `rh-card.umd.js` and `rh-card.js` for example), but matching the ESM version (`rh-card.js`) is much harder.  `*.umd.js` is easy to match precisely, but `*.js` overreaches and matches the gulpfile, storybook file, and rollup config as well.  So for now at least, this only applies to the UMD builds.

skip diff and merging on *.umd.js files

---

package.json
scripts/build.sh
scripts/test.sh

This extends #256 to `test` and `build`.  Allows running builds and tests like:
```
npm run build pfe-card pfe-cta
```
Or
```
npm test pfe-datetime
```

add easy syntax for building/testing certain elements

---

themes/cp-theme/red-hat-sass/variables/_typography.scss

This changes the base font size from a string to a unit, so that it can be multiplied.

fix scss compilation

---

elements/pfe-autocomplete/LICENSE.txt
elements/pfe-avatar/LICENSE.txt
elements/pfe-band/LICENSE.txt
elements/pfe-sass/LICENSE.txt

Minor clean-up branch updating remaining 2018 references in our component licenses to 2019.

Update date on licenses to 2019

---

elements/pfe-avatar/README.md

The attribute names in code samples of the pfe-avatar README were out of date.  Fixed!

fix pfe-avatar README attribute names

---

scripts/deploy-docs.sh

The script that calls hugo-check.sh was referring to the wrong directory, and this PR fixes that problem.   The hugo check script may have other issues on Macs, but this is only meant to fix the incorrect-directory issue.

fix the directory of the hugo-check.sh call

---

.storybook/utils.js

Current storybook tools parse html in order to inject the slot tags appropriately and allow us to use an object definition for tags.  This PR adds support for self-closing tags to those utilities such as `<img/> <br/> <hr/>` etc. that do not contain "content".

Update Storybook utils to support self-closing tag

---

elements/pfe-content-set/demo/index.html

This adds `<meta name="viewport" value="...">` to the pfe-content-set demo page.  Without it, the content set fails to detect the actual width of the screen in some situations (like devtools responsive mode).

add 'viewport' meta tag to pfe-content-set demo

---

elements/pfelement/src/pfelement.js

This belongs in the compiled asset, not the source.

remove sourceMappingURL from src/pfelement.js

---

elements/pfe-avatar/demo/index.html
elements/pfe-avatar/src/hslrgb.js
elements/pfe-avatar/src/pfe-avatar.js

Fixes two problems with IE11:
- `PFelement.var()`, used to get the current value of CSS variables, doesn't work in IE11 (or anywhere with shadyCSS I would bet).  The size of avatars is controlled with a CSS variable so the size wasn't available in IE11.  This adds a fallback of 128x128.
- IE11 doesn't accept decimals in rgb values (at least not for canvas fillStyle).  To fix, I floored the values.  `rgb(128.555, 16, 71.0)` will now be `rgb(128, 16, 71)`.
IE11 screenshot

fix pfe-avatar in ie11

---

elements/pfe-accordion/demo/index.html
elements/pfe-accordion/src/pfe-accordion-header.html

When ShadyCSS is present and a pfe-accordion-header is inside a form tag, the button inside the pfe-accordion-header will cause the parent form tag to submit.
Fixes #473
http://localhost:8000/elements/pfe-accordion/demo/
---
* If a browser is using ShadyCSS (I'm looking at you Edge and IE11), clicking on a pfe-accordion-header inside a form tag will cause the form to submit. All we did to fix this was add `type="button"` to the button in pfe-accordion-header to fix the issue.
1. Open the pfe-accordion demo file in your browser and click on …

adding type="button" to the button in the header

---

docs/content/develop/step-2b.md
elements/pfe-accordion/demo/index.html
elements/pfe-autocomplete/demo/index.html
elements/pfe-avatar/demo/index.html
elements/pfe-band/demo/index.html
elements/pfe-card/demo/index.html
elements/pfe-card/demo/pfe-card.story.js
elements/pfe-card/test/pfe-card_test.html
elements/pfe-content-set/demo/index.html
elements/pfe-cta/demo/index.html
elements/pfe-datetime/demo/index.html
elements/pfe-health-index/demo/index.html
elements/pfe-icon-panel/demo/index.html
elements/pfe-icon/demo/index.html
elements/pfe-markdown/demo/index.html
elements/pfe-number/demo/index.html
elements/pfe-page-status/demo/index.html
elements/pfe-tabs/demo/index.html
elements/pfelement/demo/index.html

* Integration with Netlify will help us preview PRs in the browser so we don't always have to pull the branch down locally just to see the changes
---
* I had to switch all of the references to the polyfills to point to cdnjs since we won't have Netlify run spandx.

setting polyfills to be loaded from cdn so pages will work with netlify

---

elements/pfe-accordion/package.json
elements/pfe-card/package.json
elements/pfe-cta/package.json
elements/pfe-datetime/package.json
elements/pfe-health-index/package.json
elements/pfe-icon-panel/package.json
elements/pfe-icon/package.json
elements/pfe-layouts/package.json
elements/pfe-number/package.json
elements/pfe-sass/package.json
elements/pfe-tabs/package.json
elements/pfelement/package.json

---
`gitHead` is a property that gets added to package.jsons by Lerna, during `lerna publish`.  It's a temporary property that gets removed after `lerna publish` concludes.  There are some elements that were committed with `gitHead` in their package.json long ago (prerelease.4 era) and this PR removes them.

remove 'gitHead' properties from some package.jsons

---

scripts/release.sh

Annotate tags when releasing.  This will probably fix lerna versioning.  Also, must not squash commitss when merging release PRs.

create annotated tags

---

lerna.json
scripts/release.sh

This PR teaches lerna to ignore built assets when figuring out whether a component has changed. Props to @kylebuch8 for finding the setting.

Lerna ignore built

---

scripts/release.sh

Lerna is not considering tags that are introduced to `master` in a merge.  This PR changes that.
https://github.com/lerna/lerna/tree/master/commands/version#--include-merged-tags

consider merged tags when evaluating changed components

---

scripts/release.sh

Currently when the release script is aborted (from an error, or ctrl+c, or answering 'No' to a prompt), the rest of the commands continue to execute.  That's bad, so this PR uses `set -e` to abort the whole script.  It also goes one step further and adds a few other '[strict mode](http://redsymbol.net/articles/unofficial-bash-strict-mode/)' tests for better reliability.

cleanly exit release script if any command errors

---

scripts/release.sh

This removes the "strict mode" (`set -euo pipefail`) from release.sh, but keeps the "exit immediately if any subcommand fails" behavior (`set -e`).

Be less strict in release.sh

---

docs/content/getting-started/component-status.md

Fixing the overflowing readiness chart on the docs site; currently its too wide & doesn't scroll https://patternfly.github.io/patternfly-elements/getting-started/component-status/
Testing instructions
cd docs
hugo server -d
visit http://localhost:1313

Fix overflow on component availability chart

---

CHANGELOG-prerelease.md
elements/pfe-card/package.json

---
pfe-card had two `files` properties in its package.json, which led to no files being published.  This PR corrects that.
```
cd elements/pfe-card
npm publish --dry-run
```
Verify in the output that "Tarball Contents" lists files in the `dist` directory, like so:
```
npm notice === Tarball Contents ===
npm notice 1.4kB  package.json
npm notice 1.1kB  LICENSE.txt
npm notice 4.6kB  README.md
npm notice 196B   dist/pfe-card--lightdom.css
npm notice 16.8kB dist/pfe-card--lightdom.css.map
npm notice 180B   dist/pfe-card--lightdom.min.css
npm notice 202B   dist/pfe-card--lightdom.min.css.map
npm notice 19.2kB dist/pfe-card.js
npm notice 24.5kB dist/pfe-card.js.map
npm notice 16.6kB dist/pfe-card.min.js
npm notice 22.9kB dist/pfe-card.min.js.map
npm notice 23.7kB dist/pfe-card.umd.js
npm …
```

fix pfe-card's published files

---

elements/pfe-content-set/README.md
elements/pfe-content-set/demo/index.html
elements/pfe-content-set/src/pfe-content-set.js
elements/pfe-content-set/src/pfe-content-set.json
elements/pfe-content-set/test/pfe-content-set_test.html

feat: add align attribute to pass down to tabs on render

---

docs/assets/sass/pfelements.scss

```
cd /docs
hugo server -D
```
Then check localhost:1313/getting-started/
Put the mouse cursor over the side nav and try to scroll down. It should be scrollable now. 
Eventually the nav should use accordions and then we can bring back the sticky positioning.

Fix hugo nav scroll issue

---

CHANGELOG-prerelease.md
lerna.json

Update lerna's `ignoreChanges` patterns so that committing compiled assets doesn't trigger version bumps in every element, during every release.  After this change, we should go back to the happy path of only the elements that change getting version bumps.

build: ignore compiled assets when determining version bumps

---

CHANGELOG-prerelease.md
elements/pfe-cta/src/pfe-cta.scss

---
* Animation on hover for the default CTA was accidentally regressed; this branch brings that back
1. Compile the pfe-cta component
2. Hover over the default style CTA
3. The arrow should subtly bounce to the right

fix: pfe-cta animation effect

---

elements/pfe-sass/mixins/_custom-properties.scss

Rendered CSS was:
```
--theme: var(var(--pfe-theme--color--surface--darkest--theme, dark), dark);
```
is now
```
--theme: var(--pfe-theme--color--surface--darker--theme, dark)
```
Look for dark text on a dark background on 
http://localhost:8000/elements/pfe-accordion/demo/
or 
http://localhost:8000/elements/pfe-band/demo/

DE21128-broadcast-theme-hooks fix: remove double var wrapper

---

CHANGELOG-prerelease.md
elements/pfe-sass/functions/_custom-properties.scss

* The zindex function was printing variables incorrectly without the string `zindex` in the middle.  
- Note the var names in the theme: https://static.redhat.com/libs/redhat/redhat-theme/3/advanced-theme.css
- Compare CSS files like pfe-modal.css and pfe-navigation.css. 
- https://web-dev-drupal-webux3.dev.a1.vary.redhat.com/en/services/training/rh024-red-hat-linux-technical-overview

fix:  add the word "zindex" back to z-index variable names

---

CHANGELOG-prerelease.md
docs/content/getting-started/_index.md
docs/content/theme/pfe-theme-slots.md
elements/pfe-styles/demo/index.html
elements/pfe-styles/src/pfe-base.scss
examples/index.html

* Link(s) to demo pages where this element can be viewed: http://localhost:8000/elements/pfe-styles/demo/
---
* Added broadcast variables by default, so links pick up theme colors.  The demo file now has 
```
:root {
--pfe-theme--color--link: green;
}
```
which is reflected in the green link 
1. 

Add broadcast variables to pfe-base.css

---

elements/pfe-accordion/package.json
elements/pfe-autocomplete/package.json
elements/pfe-avatar/package.json
elements/pfe-band/package.json
elements/pfe-card/package.json
elements/pfe-collapse/package.json
elements/pfe-content-set/package.json
elements/pfe-cta/package.json
elements/pfe-health-index/package.json
elements/pfe-icon-panel/package.json
elements/pfe-icon/package.json
elements/pfe-markdown/package.json
elements/pfe-modal/package.json
elements/pfe-navigation/package.json
elements/pfe-page-status/package.json
elements/pfe-progress-indicator/package.json
elements/pfe-sass/package.json
elements/pfe-select/package.json
elements/pfe-styles/package.json
elements/pfe-tabs/package.json
elements/pfe-toast/package.json
lerna.json

Tag: [v1.0.0-prerelease.33](https://github.com/patternfly/patternfly-elements/releases/tag/v1.0.0-prerelease.33)
- [5ad398](https://github.com/patternfly/patternfly-elements/commit/5ad3983b9ead73cf2db30fd0bc52aada334c6961) Disclosure accordion variant
- [3ccec6](https://github.com/patternfly/patternfly-elements/commit/3ccec6c82efc52aae67b74072b6c0b8ff1b47f23) Update pfe-cta to include broadcast variables for all variants [#659](https://github.com/patternfly/patternfly-elements/issues/658)

Release/v1.0.0 prerelease.33

---

CHANGELOG-prerelease.md
elements/pfe-cta/src/pfe-cta--lightdom.scss

* Fix [issue 664](https://github.com/patternfly/patternfly-elements/issues/664)
---
* Add z-index to link inside pfe-cta
1.  Test the default, primary & secondary CTA buttons in all browsers; the link should be clickable
https://web-dev-drupal-carobert.dev.a1.vary.redhat.com/en/web-components-demo#
([note that the padding issue is being worked on here](https://github.com/patternfly/patternfly-elements/pull/665) )

Bug fix: issue 664 - pfe-cta link clickability in Edge & IE

---

elements/pfe-navigation/demo/index.html
elements/pfe-navigation/src/pfe-navigation--lightdom.scss
elements/pfe-navigation/src/pfe-navigation-item.scss
elements/pfe-navigation/src/pfe-navigation.scss
elements/pfe-sass/mixins/_components.scss

- Remove extra padding from tray footer https://www.evernote.com/l/AA705fQDYmlBI5mMmFRJmyG7FJAtDJNXVwU
- At wide tablet breakpoint, menu icon drifts away from the other utility icons | https://www.evernote.com/l/AA6-dT5MQRdIC6YoeArb3pOD45LT045fTHI
- Width of the menu sometimes extends beyond the page content | https://www.evernote.com/l/AA48RyYWVd1B5ISWIyzQxan36qrHzjFMTts
---
https://web-dev-drupal-webux3.dev.a1.vary.redhat.com/fr

Adjust pfe-nav spacing and alignment; remove extra footer padding

---

CHANGELOG-prerelease.md
elements/pfe-cta/src/pfe-cta.scss

* Link(s) to demo pages where this element can be viewed: https://web-dev-drupal-sshell.dev.a1.vary.redhat.com/en
---
* SVG is hidden on CTAs which have the pfe-priority attribute
1. checkout older safari versions and test the main menu to ensure no arrow is appearing. 

added fix for nav priority links rendering with arrow

---

elements/pfe-card/demo/index.html
elements/pfe-cta/demo/index.html
elements/pfe-icon-panel/demo/index.html
elements/pfe-icon/demo/index.html
elements/pfe-tabs/demo/index.html

* Update `pfelement/pfelement.min.css` in demo files to `pfelement/dist/pfelement.min.css`
---
1. Open the demo files and make sure that pfelement.min.css is not listed as a 404:
- https://deploy-preview-704--happy-galileo-ea79c4.netlify.com/elements/pfe-card/demo/
- https://deploy-preview-704--happy-galileo-ea79c4.netlify.com/elements/pfe-cta/demo/
- https://deploy-preview-704--happy-galileo-ea79c4.netlify.com/elements/pfe-icon/demo/
- https://deploy-preview-704--happy-galileo-ea79c4.netlify.com/elements/pfe-icon-panel/demo/
- https://deploy-preview-704--happy-galileo-ea79c4.netlify.com/elements/pfe-tabs/demo/ …

chore: Fix a typo in the demo files causing pfelement.min.css to 404

---

CHANGELOG-prerelease.md
docs/content/develop/step-5.md
docs/layouts/_default/list.html
docs/layouts/_default/single.html
docs/layouts/partials/header.html

The release script still returns to master branch, so there are two PRs to update master with prerelease 38.
This one which updates docs & changelog, [then this one](https://github.com/patternfly/patternfly-elements/pull/715) generated by the script that updates the package files.

changelog & doc updates

---

.env.example
.gitignore
package-lock.json
package.json
spandx.config.js

Adding dotenv package
Defaulting localhost to 'localhost', but .env file can override that
Added example .env file
Ignoring .env file
1. `npm i` to get new additions to build.
1. Checkout branch and try to run `npm start` without adding a `.env` file, should provide a server at `http://localhost:8000/examples`
2. Save `.env.example` as `.env` and add a domain of your choosing
3. Run `npm start` and you should get `http://YOURHOSTNAME:8000/examples`

feat: Adding ability to configure the localhost domain

---

spandx.config.js

Turn the dotenv LOCALHOST check in spandx.config.js into a simpler one liner.

simplify the dotenv check in spandx.config.js

---

CHANGELOG-prerelease.md
elements/pfe-accordion/src/pfe-accordion.js
elements/pfe-content-set/demo/index.html
elements/pfe-content-set/src/pfe-content-set.js
elements/pfe-content-set/test/pfe-content-set_test.html

Fixes #720
1. View the "Using pfe-color to control the theme" section of the demo.
2. Verify that the "on" attribute has been added to both the tabs and the accordion.
3. Verify that the newly added tests for pfe-content-set are passing

fix: cascading the "on" attribute on pfe-content-set

---

.prettierignore

This extends the list of files ignored by prettier to include `scss`, `css`, `html`, and `md`.  Those filetypes were untintentionally being prettier-ified by an error in #726.

fix: run prettier only on js and json

---

CHANGELOG-prerelease.md
elements/pfe-cta/demo/demo.css
elements/pfe-cta/demo/index.html
elements/pfe-cta/src/pfe-cta.html
elements/pfe-cta/src/pfe-cta.scss
elements/pfe-sass/mixins/_mixins.scss
examples/index.html

[Resolves Issue #679](https://github.com/patternfly/patternfly-elements/issues/679)
https://deploy-preview-765--happy-galileo-ea79c4.netlify.com//elements/pfe-cta/demo/
---
* Used nobreak space in the template + white-space:nowrap to force the arrow to stick to the last word in the CTA. Then reset the white-space on the link inside the CTA. Firefox understands the box model differently, so there is a browser specific style to limit the width of the CTA so the arrow does not get cut off.
Use the resize box on the pfe-cta demo page (halfway …

fix: pfe-cta arrow wrap issue #679

---

CHANGELOG-prerelease.md
docs/content/develop/step-2a.md
elements/pfe-navigation/src/pfe-navigation--lightdom.scss

* Link(s) to demo pages where this element can be viewed: https://web-dev-drupal-anbartle.dev.a1.vary.redhat.com/de
---
* Set ms grid rows and grid columns for items in the footer tray. 
* In mobile displays set `space-between: justify-content` so that CTAs with longer text do not butt up against each other.
* Vertically centered CTAs in footer tray.
* Updated space above and below the CTAs in the tray footer to be ~40px.

fix: pfe-navigation cta overlap bug

---

CHANGELOG-prerelease.md
elements/pfe-health-index/README.md
elements/pfe-health-index/demo/index.html
elements/pfe-health-index/src/pfe-health-index.html
elements/pfe-health-index/src/pfe-health-index.js
elements/pfe-health-index/src/pfe-health-index.json
elements/pfe-health-index/src/pfe-health-index.scss
elements/pfe-health-index/test/pfe-health-index_test.html

Fixes #788
Tested in all browsers and it renders fine.

feat: pfe-health-index size="mini" version

---

CHANGELOG-prerelease.md
elements/pfe-tabs/README.md
elements/pfe-tabs/demo/index.html
elements/pfe-tabs/src/pfe-tabs.js
elements/pfe-tabs/src/pfe-tabs.json
elements/pfe-tabs/test/pfe-tabs_test.html
examples/index.html

Test by opening this demo page: http://localhost:8000/elements/pfe-tabs/demo/#tab-history
Click on each of the tabs and you should see the URL update with the id of the selected tab.
To test the feature where the correct tab opens on page load based on a query string parameter, open this page: http://localhost:8000/elements/pfe-tabs/demo/?my-tabs=tab3#tab-history. The third tab should be open on page load.
Fixes #562

feat: pfe-tabs keep history on tab click and open tab based on url parameters

---

CHANGELOG-prerelease.md
elements/pfe-cta/demo/demo.css
elements/pfe-cta/demo/index.html
elements/pfe-cta/src/pfe-cta.scss

1. Resolves issue where default pfe-ctas are wrapping when there is still enough room.  
2. Resolves issue where priority CTAs wrap to two lines and text is left aligned. It should be centered.
Preview page with fixes:
https://deploy-preview-791--happy-galileo-ea79c4.netlify.com/elements/pfe-cta/demo/

Us250350 pfe-cta wrapping issues

---

elements/pfe-select/src/pfe-select.scss

Currently the pfe-select options use the system font:
This update adds the font-family variable to the `::slotted(select) {` selector. 
To test, go to the [demo page](https://deploy-preview-794--happy-galileo-ea79c4.netlify.com/elements/pfe-select/demo/) and add the links to the redhat font & theme to the demo file head via web inspector:
http://pastebin.test.redhat.com/846613
Or add this to the body tag ;)
```
--pfe-theme--font-family: "Comic Sans MS";
```

Add support for font family to select options

---

CHANGELOG-prerelease.md
elements/pfe-navigation/src/pfe-navigation--lightdom.scss

* Link to discovery documentation (should contain all the planning and requirements for this work):
- See the `DISCOVERY.md` template at the root of the project
---
As an SEO expert, I would like the ability to remove heading tags from the navigation, without styles changing. Currently rhdotcom relies on the h3 line-height to control the spacing between the icon and the text. 
*
When viewing the pfe-navigation in my browser, I should be able to change the tag that contains the `slot=trigger` to a div, p, h2, h1, and not see any difference in the space between the icon and the tag. …

fix: set consistent line-height for pfe-nav triggers

---

CHANGELOG-prerelease.md
elements/pfe-cta/src/pfe-cta.scss

**What has changed and why**
Set the default pfe-cta font-size to be larger (18px) than the font-size for pfe-priority ctas (16px).

fix: set pfe-cta with the priority attribute relative to default pfe-cta font-size

---

CHANGELOG-prerelease.md
elements/pfe-tabs/demo/index.html
elements/pfe-tabs/src/pfe-tabs.js
elements/pfe-tabs/src/polyfills--pfe-tabs.js
elements/pfe-tabs/test/pfe-tabs_test.html

Fixes #805
- On your local machine, go to http://localhost:8000/elements/pfe-tabs/demo/ and scroll down to the "Tabs In Tabs" heading
- Click on Sub Tab 2 and ensure the content shows
- Click on Tab 2 and ensure the Tab 2 content shows
- Click on Tab 1 and ensure that Sub Tab 2 is still active and the Sub Tab 2 content is showing
This has been tested on:
- Chrome
- Firefox
- Safari
- Edge 80
- IE 11

fix: make it so pfe-tabs inside pfe-tabs works

---

elements/pfe-tabs/README.md
elements/pfe-tabs/src/pfe-tabs.js
elements/pfe-tabs/test/pfe-tabs_test.html

Fixes #802
- Navigate to https://deploy-preview-808--happy-galileo-ea79c4.netlify.com/elements/pfe-tabs/demo/?my-tabs=tab2 and verify that "Tab 2" is open in the "Tab History" section of the page
- Next,  navigate to https://deploy-preview-808--happy-galileo-ea79c4.netlify.com/elements/pfe-tabs/demo/?pfe-my-tabs=tab3 and verify that "Tab 3" is open in the "Tab History" section of the page
- Note the "pfe-" prefix in the URL. This has been deprecated but we're going to support it.
It _is_ expected that clicking on a different tab in the tab set will add another query string parameter to the URL. 
This has been tested on:
- Chrome
- Firefox
- Safari
- Edge 80
- IE 11 (this feature isn't supported on IE11 but it does not break tabs)

feat: Remove the "pfe-" prefix from the history feature in pfe-tabs

---

CHANGELOG-prerelease.md
elements/pfe-tabs/src/pfe-tabs.js
elements/pfe-tabs/test/pfe-tabs_test.html

fix: removing stopPropagation from pfe-tabs click and keydown events

---

CHANGELOG-prerelease.md
elements/pfe-tabs/src/pfe-tabs.js

Fixes #836
- [Open the demo page for pfe-tabs](https://deploy-preview-838--happy-galileo-ea79c4.netlify.app/elements/pfe-tabs/demo/) in IE11
- Go to the very bottom of the demo page to the "Dynamically Adding a Tab and Tab Panel" section
- Click on the "Add a Tab and Tab Panel" button and validate that a new tab is added to the tab set
- Click on the new tab and ensure that the tab opens

fix: pfe-tabs adding dynamic tab in IE11

---

elements/pfe-icon/README.md

Fixing typo found by https://github.com/patternfly/patternfly-elements/issues/833

docs: typo in pfe-icon README

---

CHANGELOG-prerelease.md
elements/pfe-tabs/demo/index.html
elements/pfe-tabs/src/pfe-tabs.js
elements/pfe-tabs/test/pfe-tabs_test.html

- Visit the [demo page](https://deploy-preview-846--happy-galileo-ea79c4.netlify.app/elements/pfe-tabs/demo/#add-text-to-tab-and-panel)
- Add text into the "Additional Tab Text" input field and hit the tab key
- Add text into the "Additional Panel Text" input field and hit the tab key
- Validate that there are no errors in the console relating to `Cannot read property 'toLowerCase' of undefined`

fix: pfe-tabs - Issue 845 text added to tab or panel error

---

CHANGELOG-prerelease.md
elements/pfe-card/README.md
elements/pfe-card/demo/index.html
elements/pfe-card/src/pfe-card.scss
elements/pfe-card/test/pfe-card_test.html

This is actually @eyevana's PR that she graciously merged into my card PR and now I'm pulling it back out so it can be moved through more quickly.
---
Link(s) to demo page:
- [pfe-card demo page](https://deploy-preview-856--happy-galileo-ea79c4.netlify.app/elements/pfe-card/demo/) 
---
* Link to issue detailing the request: https://github.com/patternfly/patternfly-elements/issues/629
* Adding a pfe-border attribute to the card component
1. Open the [demo page](https://deploy-preview-856--happy-galileo-ea79c4.netlify.app/elements/pfe-card/demo/) .
2. Check out the first card in the first band on the …

feat: Add pfe-border styles in a separate PR

---

CHANGELOG-prerelease.md
elements/pfe-cta/src/pfe-cta.scss
elements/pfe-icon/demo/svgtest.html

Without theme: 
With RH theme:
[Design spec](https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/f1027edf-aec8-476c-a763-576c508ba029/CTA-light-theme)
1. View the [CTA demo page](https://deploy-preview-844--happy-galileo-ea79c4.netlify.app//elements/pfe-cta/demo/) & compare the default CTA to the [mockups](https://xd.adobe.com/spec/3e62e93c-8338-4f31-5040-3b81f0ed5c71-4853/screen/f1027edf-aec8-476c-a763-576c508ba029/CTA-light-theme)
- observe the spacing around the arrow, it should be closer to the text, as shown in the mockup
- Test the hover and focus states

Reduce CTA arrow spacing, bring closer to text

---

CHANGELOG-prerelease.md
elements/pfe-navigation/src/_shared-assets.scss
elements/pfe-navigation/src/pfe-navigation-item.scss

Removed max-width: 100px that was causing the accordion trigger text to wrap between 1024px and 1030px. This max-width property was causing triggers inside the menu tray accordions to wrap between ~1000px and ~1024px.
- <s>Tests have been updated to cover these changes.</s>
- <s>Documentation (README.md, WHY.md, etc.) updated or added.</s>

fix: move max-width: 100px from menu triggers to icon triggers

---

CHANGELOG-prerelease.md
elements/pfe-datetime/demo/index.html
elements/pfe-datetime/demo/pfe-datetime.story.js
elements/pfe-datetime/src/pfe-datetime.js
elements/pfe-datetime/src/pfe-datetime.json
elements/pfe-datetime/test/pfe-datetime_test.html

Closes #880
- Visit the demo page: https://deploy-preview-881--happy-galileo-ea79c4.netlify.app/elements/pfe-datetime/demo/
- Validate that the "With time zone" date is equal to "5/7/2019, UTC"

feat: pfe-datetime adding time zone attribute

---

CHANGELOG-prerelease.md
elements/pfe-tabs/demo/index.html
elements/pfe-tabs/src/pfe-tab-panel.scss

- Update pfe-tabs demo page so that it contains HTML header tags in the tab headers. 
- Add CSS so that tab-panels which are shorter than the tabs are still at least as tall as the tab headers.
Check the [demo page](https://deploy-preview-796--happy-galileo-ea79c4.netlify.com/elements/pfe-tabs/demo/), under the heading `Style: Vertical earth with custom tab typography & header tags`. Note that the first tab-panel has content which is very short, and yet the panel is at least as tall as the tabs on the left. 
The heading tags are just to show that pfe-tabs support HTML header markup.

fix: pfe-tabs vertical height

---

.github/PULL_REQUEST_TEMPLATE.md

- Add a generic pull request template in the .github folder that will load when any new PR is created
Cannot be tested until this is merged.  When a new PR is opened, this template should auto-populate.

feat: Add a default template for PRs

---

CHANGELOG-prerelease.md
elements/pfe-autocomplete/README.md
elements/pfe-autocomplete/demo/index.html
elements/pfe-autocomplete/src/pfe-autocomplete.js
elements/pfe-autocomplete/test/pfe-autocomplete_test.html

Fixes #981
pfe-autocomplete
- (#981) pfe-autocomplete: option-selected event only fires on mouse click
- [Link](https://deploy-preview-982--happy-galileo-ea79c4.netlify.app/elements/pfe-autocomplete/demo/) 
The `pfe-autocomplete:option-selected` event is now firing on either a mouse click or the press of the enter key.
1. Go to https://deploy-preview-982--happy-galileo-ea79c4.netlify.app/elements/pfe-autocomplete/demo/
2. Add this code to the console
```
document.addEventListener("pfe-autocomplete:option-selected", event => console.log("selected event", event));
```
3. Type "it" into the first input field
4. Use the down arrow on the keyboard to select "Item 1" in the droplist
5. Hit the enter key on the keyboard to select "Item 1" …

fix: fire pfe-autcomplete:option-selected event on click and enter key

---

CHANGELOG-prerelease.md
elements/pfe-health-index/src/pfe-health-index.scss

IE11 support for health index colors:
- (#992) IE11: pfe-health-index colors
- [Link](https://5e6089f7c8e38b0008963801--happy-galileo-ea79c4.netlify.com/examples/) 
Added IE11 fallback styles.
1. Open the health index demo page in IE11.
2. Ensure color renders appropriately for each state.
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) …

fix: pfe-health-index color support in IE11

---

elements/pfe-navigation/demo/index.html
elements/pfe-navigation/src/_variables-mixins.scss
elements/pfe-navigation/src/pfe-navigation.scss

---
name: CPFED-3743 Main Nav Styles
labels: ready for review
---
Updated focus styles for main menu and dropdowns, cleaned up main nav styles and double checked colors and focus/hover states with design and redhat.com example.
1. Using a keyboard, tab through the menu to see the new focus states.

Cpfed 3743 main nav styles

---

elements/pfe-sass/maps/_colors.scss
elements/pfe-sass/maps/_general.scss
elements/pfe-sass/mixins/_mixins.scss
elements/pfe-tabs/demo/demo.css
elements/pfe-tabs/demo/index.html
elements/pfe-tabs/src/pfe-tab-panel.scss
elements/pfe-tabs/src/pfe-tab.scss
elements/pfe-tabs/src/pfe-tabs.scss

https://web-dev-drupal-ktotten.dev.a1.vary.redhat.com/en/pfe-tab-test
- Remove unused variables
- Update names of variables in local map for BEM & consistency
- Move old vars to backwards-compatibility map.
- Add comments about why tab and panel variable regions are needed in local variable maps
- Deprecate unusable padding variables in parent file
- Simplify border properties; use regular css properties instead of redefining local vars as often. 
- Run prettier on the pfe-tab sass. 
- Move selectors into discreet sections of the pfe-tab file and organize the selector attributes, in order to remove duplicates
- Order:  context, variant, active/inactive, state or nth of type
- `[on="dark"][pfe-variant="earth"][aria-selected="false"]:first-of-type`
- Add links to pfe-tab demo to ensure tab …

pfe-tabs fork: Debugging tools, var name updates + backwards compatibility

---

CHANGELOG-prerelease.md
elements/pfe-accordion/src/pfe-accordion-header.scss
elements/pfe-sass/mixins/_components.scss

- On hovering over the disclosure, the padding would shift visibly when the component was expanded.
- The chevron should be pointing toward the content when the disclosure is closed and toward the panel when the disclosure is opened.
- The container should retain it's size when the disclosure is opened and closed.
- (#1002) pfe-accordion has issues with padding
- [pfe-accordion](https://deploy-preview-1003--happy-galileo-ea79c4.netlify.app/elements/pfe-accordion/demo/) 
Added context to the padding shift so that it was properly scoped.
1. Open the [demo page](https://deploy-preview-1003--happy-galileo-ea79c4.netlify.app/elements/pfe-accordion/demo/)
2. Scroll down to the disclosure.
3. Open the disclosure.
4. Hover over the header. …

fix: pfe-accordion disclosure

---

elements/pfe-navigation/demo/index.html
elements/pfe-navigation/src/_variables-mixins.scss
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss
elements/pfelement/src/pfelement.js
examples/index.html

---
name: CPFED 3779 add icons to pfe-nav menu using pfe-icon
labels: "ready for review"
---
Added icons to the menu using `pfe-icon` and refactored the aria-haspopup feature bc we should not use it on this type of navigation menu since it is not a true application menu. Refactored to use `has-dropdown` class for now but this might need to be implemented differently.

Cpfed 3779 add icons pfe nav menu

---

CHANGELOG-prerelease.md
elements/pfelement/src/pfelement.scss
elements/pfelement/test/fouc-test.html

Currently, we transition a page's `opacity` from 0 to 1 when the `unresolved` attribute is removed from the body element, or after 2s have elapsed (timing can be overridden with `--pfe-reveal-delay`), whichever comes first.  Recently, Google added a [Cumulative Layout Shift](https://web.dev/cls/?utm_source=lighthouse&utm_medium=devtools) metric to the Lighthouse tool, and it flags _some_ of our pages as having a moderate amount of layout shift.  @wesruv suggested this could be because while the body has opacity 0, it's still considered visible, so layout shifts are detected.  To remedy that, he suggested toggling `visibility` in addition to transitioning `opacity`.  This PR implements that change.
Our local tests showed that this reduced the CLS score on the project's root index.html page …

fix: improve CLS rating in lighthouse

---

CHANGELOG-prerelease.md
elements/pfelement/src/pfelement.scss
elements/pfelement/test/pfelement_cascade_attribute_test.html
elements/pfelement/test/pfelement_emitEvent.html
elements/pfelement/test/pfelement_logging_test.html
elements/pfelement/test/pfelement_test.html

The pfelement tests weren't running, this restores them so they'll be run along with the rest of the test suite.
pfelement tests weren't running, seemingly because they were attempting to import pfelement.js from the package root, instead of the dist directory.
Try running `npm test` and look for pfelement tests, or `npm test pfelement` and verify that more than 0 tests run (previously, it would "pass" with zero tests run).
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribut …

fix: pfelement - restore pfelement tests

---

elements/pfe-navigation/demo/index.html

updated custom link icon placeholder to globe icon, could not use bell icon yet bc it is not in avalon-docs. used globe instead for now bc it is used as the language switcher icon on redhat.com so is a realistic icon example

CPFED-3779: updated custom link icon placeholder 

---

elements/pfe-navigation/README.md
elements/pfe-navigation/demo/index.html
elements/pfe-navigation/src/_variables-mixins.scss
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss

Refactored open and close dropdown code
Added Esc key functionality
Updated variable and function names to be more consistent and easier understand
Added height calculation JS to secondary link dropdowns, but isn't working yet
Fixed bug where height of dropdown wasn't correct on resize
Fixed animation for dropdowns
Made sure 'heavy' DOM manipulation/reading isn't done all the time
Added dev only console logging when heavy processes are run
Moved more HTML class/id setup to JS instead of making stakeholders do it
Made sure words in the top bar don't wrap
Fixed jumping text
Fixed bug where single column didn't have padding at smaller breakpoints

CPFED-3790, CPFED-3791, CPFED-3792: Lots of features & bug fixes

---

docs/content/theme/theme-palette.md

Update docs to reflect new variables

docs: Theme palette variables update

---

docs/config.toml

Kendall reported that HTML was being elided from markdown docs.  Luke found in [the hugo 0.60.0 release notes](https://gohugo.io/news/0.60.0-relnotes/) that a new config option is needed to re-enable embedding HTML.
Configured hugo's new markdown parser, goldmark, to allow HTML embedding.
1. run the hugo server locally, look at docs pages with embedded HTML and ensure the HTML is rendering properly.
2. poke around other pages to be sure this change didn't break anything (there coud _potentially_ be docs pages with buggy HTML that was meant to be embedded, but never was, and once it is, the bugs will crawl out.)
**Be sure to share your …

docs: allow embedding HTML in markdown docs

---

index.html

- Fixing Lighthouse issues by adding alt tags to images. No text in the alt tags are necessary since they are purely decorative.
- Adding some additional CSS to the CTAs in the header so they are the same size on a mobile device.
Before Lighthouse fixes
After Lighthouse fixes
Before CTA sizing fix
After CTA sizing fix
- [Link](https://deploy-preview-1022--happy-galileo-ea79c4.netlify.app/) 

docs: demo homepage - adding alt tags to images and fixing cta alignment

---

elements/pfe-navigation/README.md
elements/pfe-navigation/demo/index.html
elements/pfe-navigation/documentation/implementation.md
elements/pfe-navigation/src/_variables-mixins.scss
elements/pfe-navigation/src/pfe-navigation--lightdom.scss
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss

Added .pfe-navigation__fallback-links to substite for secondary links in no-JS version
Removed the need for .pfe-navigation__dropdown-wrapper in LightDOM markup, adding it in JS
Removing style attribute in demo page and moving styles to pfe-navigation--lightdom.[s]css
Adding has-dropdown class dynamically
Reworked has-dropdown class to BEM format

CPFED-3754: Developer Experience improvements and documentation updates

---

docs/config.toml

Disable the broken code highlighting in docs code blocks.  It was caused by a change in Hugo v0.60 which enabled highlighting by default, whereas we had been relying on it being false by default in previous versions.

docs: fix broken code highlighting in docs' code blocks

---

elements/pfe-navigation/demo/index.html
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
examples/index.html

---
name: Cpfed 3789 update aria features for shadow DOM buttons and dropdown content
labels: "ready for review"
---
added aria-hidden/aria-expanded to shadow DOM for the other dropdowns, added some notes on things to regroup on, did some more keyboard testing and fixed aria-hidden issue for search and all red hat buttons but not dynamically, updated alt text of images, removed aria-expanded and has-dropdown from no js menu example.

Cpfed 3789 update aria util btns

---

CHANGELOG-prerelease.md
elements/pfe-autocomplete/src/pfe-autocomplete.js
elements/pfe-autocomplete/test/pfe-autocomplete_test.html

Fixes #1045
Our analytics teams have requested a custom event to be fired when the pfe-autocomplete dropdown is shown to a user. They need this to help track the usage of the component. This pull request fires a `pfe-autocomplete:options-shown` event when the dropdown is shown to the user.
- (#1045) pfe-autocomplete: fire custom event when dropdown is shown
- [Link](https://deploy-preview-1046--happy-galileo-ea79c4.netlify.app/elements/pfe-autocomplete/demo/) 
1. [Go to the demo page](https://deploy-preview-1046--happy-galileo-ea79c4.netlify.app/elements/pfe-autocomplete/demo/)
2. Add the following code block in the developer tools console
```
const pfeAutocomplete = document.querySelector("pfe-autocomplete"); …
```

feat: pfe-autocomplete - fire custom event when dropdown is shown

---

.github/workflows/automerge.yml
.github/workflows/visualtests.yml
.travis.yml
CHANGELOG-prerelease.md

Fixes #1053
Our visual regression tests continue to fail because we are trying to run too many parallel tests at once. This PR disables the visual regression tests on every PR. We'll have to run the visual regression tests manually until we figure out how to queue our BrowserStack tests better.
- (#1053) visual regression testing - need to set it so we're only running it manually

test: disabling visual regression testing in favor of manual running

---

CHANGELOG-prerelease.md
README.md
package.json

Currently the build is run after `npm install` but our watch and test commands all include the build as well.  This makes the post-install step duplicative and no longer needed.  Remove it from post-install will be more efficient.

feat: Remove build from postinstall

---

elements/pfe-navigation/demo/index.html
elements/pfe-navigation/src/_variables-mixins.scss
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss

feat: Fixing and refactoring resize and interaction behavior
Added pre- and post- resize adjustment functions to make sure element state (e.g. aria-hidden) is always set correctly and to hide jank
Added utility functions to add open/close attributes for dropdowns and remove them entirely
Added utility function to set correct mobile dropdown, because it changes depending on breakpoint
Made processLightDom function more performant by delaying write to DOM until it was finished updating the cloned section from the light DOM
Reworked markup for secondary links to be more semantic (in a ul) and added spot for search to be added to at desktop sizes
Renamed the separator class for dropdowns to follow BEM standards
Replaced debounce function with one that allows for function to run at the start …

feat: Fixing and refactoring resize and interaction behavior

---

elements/pfe-navigation/demo/single-nav.html
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss
examples/index.html

---
name: Add Overlay Features
labels: "feature, ready for review"
---
- add overlay feature that is visible when menu is open and hidden when menu is closed
- add overlay feature that allows user to close entire menu when the overlay is clicked
- insure that aria states toggle appropriately when overlay is clicked to close menu
- overlay is hidden when escape key is pressed and menu closes
- add demo page that shows only one single nav on the page
1. Pull down changes from this branch
2. run `npm start`
3. run `npm run dev pfe-navigation`
4. navigate to `http://localhost:8000/elements/pfe-navigation/demo/single-nav.html`
5. Open each dropdown on desktop
6. Close each dropdown on desktop by clicking the overlay div 
7. Open the menu items on mobile
8. Close the menu items on mobile by …

Cpfed 3809 pfe nav add overlay

---

elements/pfe-navigation/src/_variables-mixins.scss
elements/pfe-navigation/src/pfe-navigation--lightdom.scss
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss

---
name: CPFED-3847 back to menu button
labels: "feature, ready for review"
---
- added back to menu button feature inside of mobile all red hat menu
- added focus state management for back to menu button and added function for development to log focused element to console for debugging
- cleaned up some unneeded css
- added styles for back menu button
- updated some of the handlers to point to the original variable for the site switcher wrapper so that code was less redundant 
- added aria-hidden true for all red hat icon
- updated function for open attr function to also set the aria-controls id
- cleaned up inital state setting of aria attr for mobile menu and util buttons
- add overflow x hidden to mobile menu to make the all red hat menu not scrollable until you click on the all red …

Cpfed 3847 menu back button

---

CHANGELOG-1.x.md
elements/pfe-accordion/src/pfe-accordion-panel.scss

Setting border-box on pfe-accordion-panel adds the border and shadow back to the right of the accordion panel.
- (#1183) pfe-accordion: accordion panel does not have a border or shadow on the right
- [Link](https://5e6089f7c8e38b0008963801--happy-galileo-ea79c4.netlify.com/examples/) 
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) …

fix: pfe-accordion adding right border and shadow back

---

elements/pfe-navigation/demo/single-nav-sticky.html
elements/pfe-navigation/src/pfe-navigation.js

---
name: Close any open menus when nav loses focus
labels: "feature, ready for review"
---
Added feature to close any open menu dropdowns when the entire nav loses focus so that keyboard users cannot get to the rest of the page content with the nav still open.
1. Pull down changes
2. Tab through nav and onto the page content with any dropdown menu open
3. The dropdown menu should close when the last item in the nav loses focus and the focus is on the page content and not the nav.

Cpfed 3850 close menu nav loses focus

---

.github/workflows/tests.yml

https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This PR patches the deprecation of add-path which is used in the plugins for the test workflow.

ci: Patch the add-path deprecation for the build task

---

.github/workflows/automerge.yml

Reduce how often the automerge script attempts to run by limiting its trigger events.
`API rate limit exceeded for installation ID 7180918. | Try to merge the PR if allowed: .github#L1`

CI: Reduce when automerge tries to run for API overages

---

elements/pfe-button/package.json

Fixes #1228
`pfe-button` had the `@patternfly/pfelement` dependency pointing to a prerelease version of `pfelement`. 
- (#1228) pfe-button dependency points to prereleases of pfelement
- The `pfelement` dependency in package.json has been updated to `"@patternfly/pfelement": "^1.0.0"`
- The dependencies for `pfe-sass` and `gh-pages` have been removed

bug: updating pfe-button dependency to point at pfelement 1.0.0

---

CONTRIBUTING.md

Emphasize opening an issue in the contribution guidelines over opening a PR.  This is so we can prioritize issues before coding has been done.

doc: Update contributing guidelines to emphasize issues

---

.storybook/utils.js
CHANGELOG-1.x.md
elements/pfe-accordion/demo/pfe-accordion.story.js
elements/pfe-autocomplete/demo/pfe-autocomplete.story.js
elements/pfe-avatar/demo/pfe-avatar.story.js
elements/pfe-badge/demo/pfe-badge.story.js
elements/pfe-band/demo/pfe-band.story.js
elements/pfe-button/demo/pfe-button.story.js
elements/pfe-card/demo/pfe-card.story.js
elements/pfe-collapse/demo/pfe-collapse.story.js
elements/pfe-content-set/demo/pfe-content-set.story.js
elements/pfe-cta/demo/pfe-cta.story.js
elements/pfe-datetime/demo/pfe-datetime.story.js
elements/pfe-dropdown/demo/pfe-dropdown.story.js
elements/pfe-health-index/demo/pfe-health-index.story.js
elements/pfe-icon-panel/demo/pfe-icon-panel.story.js
elements/pfe-icon/demo/pfe-icon.story.js
elements/pfe-jump-links/demo/pfe-jump-links.story.js
elements/pfe-markdown/demo/pfe-markdown.story.js
elements/pfe-modal/demo/pfe-modal.story.js
elements/pfe-navigation/demo/pfe-navigation.story.js
elements/pfe-number/demo/pfe-number.story.js
elements/pfe-page-status/demo/pfe-page-status.story.js
elements/pfe-progress-indicator/demo/pfe-progress-indicator.story.js
elements/pfe-select/demo/pfe-select.story.js
elements/pfe-tabs/demo/pfe-tabs.story.js
elements/pfe-toast/demo/pfe-toast.story.js

The latest version of the storybook knobs add-on no longer separates the bridge into a polymer directory.
`npm run storybook`

fix: storybook bug

---

elements/pfe-clipboard/README.md
elements/pfe-clipboard/demo/index.html
elements/pfe-clipboard/src/pfe-clipboard.js
elements/pfe-clipboard/test/pfe-clipboard_test.html
elements/pfe-clipboard/test/pfe-clipboard_test.js

This pull request adds the `copied-duration` setting to pfe-clipboard.
pfe-clipboard
- https://github.com/patternfly/patternfly-elements/pull/1235#discussion_r556751274

Us267056 pfe clipboard  copied duration

---

elements/pfe-clipboard/src/pfe-clipboard.scss

Fixes: https://github.com/patternfly/patternfly-elements/pull/1235#discussion_r556761775

feat: added vars to control padding on host and margin on icon

---

elements/pfe-clipboard/README.md
elements/pfe-clipboard/demo/index.html
elements/pfe-clipboard/src/pfe-clipboard.html
elements/pfe-clipboard/src/pfe-clipboard.js
elements/pfe-clipboard/test/pfe-clipboard_test.js

Fixes the IE11 issue with not supporting transposeSlot functionality.  
- IE11 doesn't support slotchange
- mutation observer implementation wasn't a 1:1 alternative of slotchange
The two issues that we would need to address with default slots in the future are:
- Default slots get wiped out with whitespaces
- Eliminates the power of a web component "gobbling up lightdom".  The technique were you put fallback content inside the web component knowing that it's going to get cleared out when the web component sets up.
For now, let's just remove the default slot until we come up with a bulletproof way of having named slots and default slots.

feat: removing default slot

---

elements/pfe-datetime/test/old-test/pfe-datetime_test.js
elements/pfe-datetime/test/pfe-datetime_test.js

Fixes #1320
pfe-datetime tests are currently failing 
(#1320)
No preview. The tests should just pass.
Something has changed with how Chrome is doing localization for the Spanish locale. I had to remove the period in "lunes, 02 de ene de 2006" (was previously lunes, 02 de ene. de 2006) to get the tests to pass.
1. Run the tests

test: updating pfe-datetime Spanish locale test

---

scripts/build.sh

Currently pfe-sass is passed to the build command as if it's a component, but since components all build concurrently, this can occasionally lead to issues where pfe-sass is in the process of rebuilding and components are requesting assets from it.  By removing pfe-sass from the build (unless it is the only input provided), we are allowing lerna to pre-build pfe-sass when it is a dependency of a component.  This is partly because pfe-sass is a `devDependency` so lerna isn't bootstrapping it for us.
1. `npm run build` -> builds pfe-sass FIRST then all other components
2. `npm run build pfe-accordion` -> builds pfe-sass then pfe-accordion
3. `npm run build pfe-sass` -> builds pfe-sass only
4. `npm run build pfe-accordion pfe-band pfe-sass` -> builds pfe-sass FIRST, then pfe-accordion and …

tools: fix sass compile timing

---

.github/workflows/tests.yml
scripts/build.sh
scripts/demo.sh
scripts/deploy-docs.sh
scripts/dev.sh
scripts/hugo-check.sh
scripts/leftover-check.sh
scripts/release.sh
scripts/test.sh
scripts/watch.sh
wdio.conf.js

When a bash script is run in a GitHub Action, it opens a sub-shell which which isn't reading at tty.  Adding `export FORCE_COLOR=true` to the top of bash scripts forces the color support on in these shells.  
Voilà!  Color!
- It works!!! https://github.com/patternfly/patternfly-elements/runs/1826170121?check_suite_focus=true

CI: color flag for command line in GitHub Actions

---

CHANGELOG-1.x.md
elements/pfe-sass/mixins/_copy-mixins.scss

- pfe-styles
- https://github.com/patternfly/patternfly-elements/issues/1337
https://deploy-preview-1338--happy-galileo-ea79c4.netlify.app/elements/pfe-styles/demo/
- fix font-weight for pfe-text modifier classes within mixin
1.  Check the pfe-styles demo page, the text modifiers at the bottom should look like this: 

fix: [pfe-styles] adjust weight of text modifier classes to be lighter

---

.github/PULL_REQUEST_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE/new_component.md
.github/PULL_REQUEST_TEMPLATE/update_component.md
.github/PULL_REQUEST_TEMPLATE/update_infrastructure.md
.github/workflows/automerge.yml
.github/workflows/project.yml

- Updating `needs: code review`, `needs: branch testing`, and `needs: browser testing` to `ready:` prefix.
- The workflow_run event is not valid for automerge; throwing errors so this PR removes that event

chore: Update automerge & needs/ready labels

---

elements/pfe-content-set/src/pfe-content-set.js

Fixed small bug with setting hidden attribute to the pfe-content-set element.

fix: set hidden attribute to empty string

---

elements/pfe-primary-detail/package.json

Updates package.json to include devDependencies:
- pfe-sass: Used in compiling the CSS assets
- pfe-styles: Used on the demo page
- pfe-cta: Used on the demo page
This update is urgent because without pfe-sass as a dependency, lerna is not handling the timing of compilation correctly and it's running without the compiled assets available and throwing Sass errors.

chore: update package dependencies for primary detail

---

elements/pfe-jump-links/test/index.html
elements/pfe-jump-links/test/pfe-jump-links_test.js

Temporarily adding a skip to Vue tests on pfe-jump-links because these continue to fail on unrelated PRs.  These will be resolved in https://github.com/patternfly/patternfly-elements/pull/1278.

CI: Comment out Vue tests for jump links temporarily to prevent unrelated failures

---

elements/pfe-navigation/package.json
elements/pfe-primary-detail/package.json
elements/pfe-styles/package.json
elements/pfelement/package.json
generators/element/templates/package.json

Sometimes Netlify doesn't let the pfe-sass dependency finish building before it kicks off the build for components that have it listed as a dependency
All components should list pfe-sass as a dependency.
- (#1458)[https://github.com/patternfly/patternfly-elements/issues/1458] Issue with sass:globbing timing
- [Link](https://deploy-preview-<pr_number>--happy-galileo-ea79c4.netlify.app//examples/) 
- pfe-navigation: moved pfe-styles and pfe-sass to dependencies
- pfe-primary-detail: removed pfe-cta and pfe-styles dependency (not invoked in the component, only used on demo page); moved pfe-sass to dependency
- pfe-styles: move pfe-sass to dependency
- pfelement: move pfe-sass to dependency
- Update generator
Please **squash** when …

chore: Update pfe-sass references

---

elements/pfe-navigation-account/demo/index.html
elements/pfe-navigation-account/src/pfe-navigation-account.js

Adds everything necessary for translations. We need to make a request for most of these strings but the groundworks is in place here. To test, update the lang attribute and the correct language code should appear after "Account details".

Translate user menu

---

elements/pfe-sass/gulpfile.js
generators/element/templates/scripts/gulpfile.factory.js
scripts/gulpfile.factory.js

By setting the watch functions to async, we were telling the task to complete after firing but really we want the task to hang out until the command is cancelled.
- Removed async from the watch functions

chore: Fix watch task failure 

---

elements/pfe-accordion/demo/demo.css
elements/pfe-accordion/demo/index.html

Updating the accordion custom styles.
From:
To:
[Preview](https://deploy-preview-1589--patternfly-elements.netlify.app/elements/pfe-accordion/demo/)
Please **squash** when merging and ensure your commit message uses [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/#summary) formatting.  Documentation updates do not require a CHANGELOG entry.

fix: Updating demo custom styles

---

CHANGELOG-1.x.md
elements/pfelement/src/pfelement.js

Code actually written by @mwcz, despite being committed by @wesruv
- (#1573)
1. Add `PFElement._debugLog = true;` to `constructor()` of a component
2. Add `this.log(['foo', 'bar', 'baz'])` after `debugLog` somewhere
3. Verify that logged message prints the array so you can inspect it's values, and not as a flattened string (e.g. `[array]`)

fix: Update pfelement logging so arrays and objects get printed (#1573)

---

.github/workflows/project.yml
.github/workflows/tests.yml
elements/pfe-accordion/test/pfe-accordion_test.js

This action validates the build on master and if it failed, it opens a new issue.

chore: Add a tool to open an issue if the build on master breaks

---

CHANGELOG-1.x.md
elements/pfe-sass/functions/_custom-properties.scss

Currently, pfe-fetch can query the $LOCAL-VARIABLES map but it does not accept an optional $region variable so it cannot capture values from the map inside nested region maps.
This PR fixes that issue.
- (#1328) [feat] pfe-sass | pfe-fetch accept $region variable
- Allow pfe-fetch to receive an optional region value which it can then use to deep search $LOCAL-VARIABLES maps
1. In the pfe-cta.scss file, try: `pfe-fetch(Display, $region: arrow)` --> should output: `inline` in the _temp/pfe-cta.css file.  …

feat: Update fetch mixin to support region input (#1328) 

---

elements/pfe-navigation-account/demo/fake-wes-auth.js
elements/pfe-navigation-account/src/pfe-navigation-account.js
elements/pfe-navigation/README.md
elements/pfe-navigation/demo/access.html
elements/pfe-navigation/demo/catalog.html
elements/pfe-navigation/demo/index.html
elements/pfe-navigation/demo/index_react.html
elements/pfe-navigation/demo/index_vue.html
elements/pfe-navigation/demo/pfe-navigation.story.js
elements/pfe-navigation/demo/single-nav-sticky-alert-banner.html
elements/pfe-navigation/demo/single-nav-sticky.html
elements/pfe-navigation/demo/single-nav.html
elements/pfe-navigation/package-lock.json
elements/pfe-navigation/package.json
elements/pfe-navigation/src/pfe-navigation--lightdom.scss
elements/pfe-navigation/src/pfe-navigation.html
elements/pfe-navigation/src/pfe-navigation.js
elements/pfe-navigation/src/pfe-navigation.scss
elements/pfe-navigation/test/pfe-navigation_react_test.html
elements/pfe-navigation/test/pfe-navigation_test.html
elements/pfe-navigation/test/pfe-navigation_vue_test.html

- (#100) Description of issue
- 
1. Go here
2. Do this
1. Go here
2. Do this

CPFED-3689 breaking nav changes

---

CHANGELOG-1.x.md
elements/pfe-content-set/src/pfe-content-set.js

In the rewrite required to fix the Safari 14.1.1 issue, the ID copy from parent to nested shadow DOM component was missed.  This brings that back.
- [Link](https://deploy-preview-1653--patternfly-elements.netlify.app/elements/pfe-content-set/demo)

fix: Fix content set ID copy to shadow dom

---

elements/pfe-navigation/src/pfe-navigation.html

Changed aria-text of pfe-nav from "Main navigation" to "Main" to remove redundancy for screen readers.

CPFED-4211: change aria text for main nav to Main

---

CHANGELOG-1.x.md
generators/test/templates/_element.spec.js
web-test-runner.config.mjs

1. Fixes some formatting with the generator test and updates the fixture element name to be more easily replaceable.
2. Adds a meta viewport tag for tests. This will make it easier to write browser width specific tests.
1. Check out the branch, `git checkout testing-update-docs`
2. `npm install`
3. `npm run build`
4. `npm run test:watch --element="pfe-select"`
5.  Hit the "D" key to debug in a browser.
6. Right click and inspect the document. Verify you see a `<meta name="viewport"` tag.
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute@redhat.com) mailing …

chore: Minor testing updates

---

elements/pfe-absolute-position/CHANGELOG.md
elements/pfe-absolute-position/package.json
elements/pfe-absolute-position/src/pfe-absolute-position.js
elements/pfe-popover/package.json
elements/pfe-tooltip/package.json

When a use hovers over a tooltip very quickly and repetitively it was causing warnings for `forced reflow`.  This is caused when javascript is trying to calculate styles at the same time it's applying them.  This would cause sever performance issues.
The cause is that we are trying to update the position of the tooltip when the it was about to activate.  This would allow the target to potentially move around the screen and the tooltip would always follow it.
- Go here: https://deploy-preview-1406--patternfly-elements.netlify.app/elements/pfe-tooltip/demo/
- Open dev console
- Quickly hover over the different tooltips in quick succession
- You should see a `forced reflow` warning in your console
- Go here: https://deploy-preview-1702--patternfly-elements.netlify.app/elements/pfe-tooltip/dem …

fix: [pfe-tooltip] forced reflow performance isssues

---

CHANGELOG-1.x.md
elements/pfe-jump-links/src/pfe-jump-links-nav.js

- [parseInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/parseInt) Number.parseInt doesn't work in IE11, only the globally scoped parseInt does

fix: IE11 bug for jump links 

---

CHANGELOG-1.x.md
elements/pfe-accordion/src/pfe-accordion-header.js

Regression in pfe-accordion rendering slotted content in the header region.
URL: https://patternflyelements.org/components/content-set/
1. Validate that all accordion headers render with their text and not "undefined"
1. Resize one of the panels rendering as a tabset
2. Validate that all accordion headers it uses now render with their text and not "undefined"
**Be sure to share your updates with the [patternfly-elements-contribute@redhat.com](mailto:patternfly-elements-contribute …

fix: Issue with slotted content rendering in pfe-accordion-header

---

elements/pfe-tabs/src/pfe-tabs.js

- Resolves #1755 
- [Link](https://deploy-preview-1766--patternfly-elements.netlify.app/elements/pfe-tabs/demo) 
- Corrected an error for setting the default selected tab index if one wasn't directly set.  Fixed infinite loop issue.
1. https://deploy-preview-1766--patternfly-elements.netlify.app/pfe-tabs/demo
2. 

fix: fix for re-renders when there is no selectedindex

---

elements/pfe-accordion/src/pfe-accordion-header.js
elements/pfe-accordion/src/pfe-accordion.js
elements/pfe-accordion/test/pfe-accordion.spec.js

When an accordion is clicked in pfe-content-set there isn't enough information to tell what has been expanded/collapsed, making analytics based on interaction impossible.
- pfe-accordion
- pfe-content-set
- (#1764 )
- Added extra keys to details on accordion events to give analytics quick access to what element has opened/closed.
1. Go to https://www.redhat.com/en/contact
2. In the console, add:
```js
document.addEventListener('pfe-accordion:expand', function(event) {
debugger;
});
```
3. Click on an accordion to expand
4. `event.details` Should have a reference to the toggle and pane that have updated
Your component should work in all of the …

fix: Adding better details to accordion events

---

CHANGELOG-1.x.md
elements/pfe-styles/demo/typography-mobile.html

Fixes names of CSS variables in demo page
- Fixes https://github.com/patternfly/patternfly-elements/issues/1781
https://deploy-preview-1782--patternfly-elements.netlify.app/elements/pfe-styles/demo/typography-mobile.html
http://localhost:8080/elements/pfe-styles/demo/typography-mobile.html
CSS variables had too many dashes, so they weren't working. Now you can see the demo of responsive typography in action.
1. Go here  https://deploy-preview-1782--patternfly-elements.netlify.app//elements/pfe-styles/demo/typography-mobile.html
2. Squish the window size down until the blue border turns orange. You should see the typography sizing on all headings and text change. 
Please **squash** when merging and ensure your commit message uses [conventional …

fix: issue-1781  Mobile typography variable names

---

elements/pfe-navigation/package.json

This adds a `^` to each PFE dependency of pfe-navigation.  The reason for removing the fixed version dependency is that when pfe-navigation is included in another project (Primer in this case), an extra copy of each fixed-version dependency is pulled in.
Example:
- Primer has `pfe-icon@^1.0.0` which resolves to `1.11.2`
- pfe-icon depends on `pfelement@^1.9.3` which resolves to `1.11.2`
- Primer has `pfe-navigation@1.0.0` which resolves to `1.0.83`
- pfe-navigation depends on `pfelement@1.9.3` which resolves to `1.9.3`
As a result, Primer winds up bundling both PFElement  `1.11.2` and `1.9.3`.

fix(deps): add ^ to pfe-nav's pfe deps to avoid duplication

---

CHANGELOG-1.x.md
elements/pfe-accordion/src/pfe-accordion-panel.scss

Adds `box-sizing: border-box;` to the accordion-panel.  Corrects the border offset in the panels.
- #1809 
- [pfe-accordion demo](https://deploy-preview-1810--patternfly-elements.netlify.app/elements/pfe-accordion/demo/?accordion-with-history=1) 
1. Go to https://deploy-preview-1810--patternfly-elements.netlify.app/elements/pfe-accordion/demo/?accordion-with-history=1
2. In the browsers network devtools, block the following file: `pfe-base.css`.  (This contains a global fix which is why we weren't seeing the issue).
3. Refresh the page with devtools open.
4. Open the first accordion item that contains a nested accordion item.  Open the nested item.
5. Verify that the right border on the nest accordion is straight.
Your component …

fix: added border-box to panel to fix border offset

---

elements/pfe-progress-steps/demo/pfe-progress-steps.html
elements/pfe-progress-steps/pfe-progress-steps-item.scss
elements/pfe-progress-steps/pfe-progress-steps.ts

This PR removes some code that was supposed to enable progress steps to have a `count` connotation.  I think this is erroneous code that snuck passed code review.  Not only doesn't it work, we don't have design specs for it.

[pfe-progress-steps] removing erroneous count property

---

docs/main.css
elements/pfe-toast/docs/index.md
elements/pfe-toast/pfe-toast.ts

Adding an `.opt-out` class for headers in the docs styles.  I added this so that the headers in `pfe-toast` can opt out.

chore: 2.0 [pfe-toast] update docs

---

elements/pfe-jump-links/demo/pfe-jump-links.html
elements/pfe-jump-links/docs/index.md
elements/pfe-jump-links/pfe-jump-links-nav.scss
elements/pfe-jump-links/pfe-jump-links-nav.ts
elements/pfe-jump-links/pfe-jump-links-panel.ts
elements/pfe-jump-links/pfe-jump-links.ts

- Update docs
- Fix that enables user to set the offset to `0`
- Fix active item indicator

fix: 2.0 pfe-jump-links doc updates and fixes

---

elements/pfe-readtime/README.md
elements/pfe-readtime/pfe-readtime.ts
package-lock.json
patches/cem-plugin-readonly+0.0.2.patch
tools/pfe-tools/custom-elements-manifest.ts
tools/pfe-tools/package.json

I updated `readtime` property on pfe-readtime to be readonly.  I can't seem to get the `cem-plugin-readonly` plugin working though.  This plugin would add a `readonly` connotation to the docs.

feat: 2.0 pfe-readtime readonly prop

---

elements/pfe-accordion/pfe-accordion-header.ts
elements/pfe-accordion/test/pfe-accordion.spec.ts

Adds unit tests for keyboard accessibility fixes in `<pfe-accordion>`
- (#1779) 
- use `delegatesFocus` when attaching `<pfe-accordion-header>` shadowroot
- unit tests for [wai-aria practices](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html)
1. ```npm run test -- --watch --group default --files elements/pfe-accordion/test/pfe-accordion.spec.ts```
1. ```npm start```
2. Manual keyboard testing according to [wai aria best practices](https://www.w3.org/TR/wai-aria-practices/examples/accordion/accordion.html)
Please **squash** when merging and ensure your commit message uses [conventional …

fix(accordion): keyboard a11y

---

elements/pfe-primary-detail/demo/pfe-primary-detail.html
elements/pfe-primary-detail/pfe-primary-detail.ts

```
Removed aria attributes from element surrounding text, only need htose on the button wrapper
Set back button text to property so we aren't reading the DOM during render (? seems like the that's recommended)
Removed unused functions made during original development, but are now unused
Updated Demo HTML, thought text in 'details' was a bug in functionality, but was content in the slot. Hopefully the slight adjustment makes that more clear.
```
This update isn't as necessary as I thought; the 'bug' I was chasing was content in `slot=details` on the first example, not duplicate content added by the component code 🤦🏼‍♂️ 
Was confused myself about how this thing is supposed to work... so that's not a great sign.
_I think_ that having the back button text be a property is probably simpler? …

pfe-primary-detail: Simplifying back button text and removing unused functions

---

elements/pfe-card/demo/pfe-card.html
elements/pfe-card/docs/index.md
elements/pfe-card/pfe-card.ts

- I moved some of the props into JSDoc to surface in CEM.

feat(pfe-card) 2.0 doc changes

---

elements/pfe-dropdown/pfe-dropdown.ts
elements/pfe-dropdown/test/pfe-dropdown.spec.ts

Removing the public `focus()` method causes an error in the following test: 
`Enter should exit open dialog and move focus to the dropdown.`.  Meaning that when you're focused on the list item and you click `Enter` on an action item it needs to programatically move the focus to `pfe-dropdown`.  Knowing that, I added a private `_focus()` method to programmatically move the focus to the button.
```
<pfe-dropdown>
#shadowRoot
<button>
```

fix: moved public focus method to private.

---

.changeset/good-actors-allow.md
.changeset/loud-cycles-vanish.md
package-lock.json
package.json
scripts/open-pr.js
tools/create-element/generator/element.ts
tools/create-element/main.ts
tools/create-element/package.json
tools/create-element/templates/element/package.json
tools/pfe-tools/README.md
tools/pfe-tools/package.json

Fixes #1884 
- replaces `inquirer` with `prompts` 
- ships pfe-tools files to npm instead of just `.ts` sources
- adds a stub README to tools
- allows generated files to use prereleases of core
1. clone a test monorepo
```bash
git clone git@github.com:bennypowers/pfe-monorepo-template.git pfe-monorepo-test
cd pfe-monorepo-test
npm ci
```
2. Now, switch directories to patternfly elements, check out this branch, then build and link create and tools
```bash
git checkout fix/create/dependencies-and-tools-files
npm run build -w @patternfly/create-element -w @patternfly/pfe-tools
cd tools/create-element
npm link
cd ../pfe-tools
npm link
```
3. Switch back to the test dir and link the PR packages
```bash
npm link @patternfly/pfe-tools
npm link @patternfly/create-element
```
4. run the generator …

Fix create dependencies, and ship tools files

---

.changeset/breezy-bikes-smell.md
elements/pfe-clipboard/README.md
elements/pfe-clipboard/demo/pfe-clipboard.html
elements/pfe-clipboard/demo/pfe-clipboard.js
elements/pfe-clipboard/docs/index.md
elements/pfe-clipboard/pfe-clipboard.scss
elements/pfe-clipboard/pfe-clipboard.ts
elements/pfe-clipboard/test/pfe-clipboard.spec.ts

- Updated accessibility features for pfe-clipboard
- Address some issues found by Lighthouse and aXe DevTools
- Fixed some comment typos
- Added appropriate aria features and js updates
- Addressed major issues found during screen reader testing.
- Updated the component to function for all users rather than just sighted mouse users
- Added default state of 4 seconds and logic to ensure that the timeout is never set below 4 seconds so that users have enough time to hear and read the text state changes
https://github.com/patternfly/patternfly-elements/issues/1873
1. Check out the fix/a11y-update-pfe-clipboard branch
1. Run npm start
1. Go to http://localhost:8000/demo/pfe-clipboard
- pfe-clipboard.ts
- Added new state property for aria-disabled to added aria features
- Added comments for …

fix: add all commits together

---

.changeset/nice-baboons-perform.md
.github/workflows/visual-regression.yml
elements/pfe-jump-links/pfe-jump-links-nav.ts
index.html

Adds aria-labelledby to jump links internal list
- closes #1765 
- Adds aria-labelledby to jump links internal list
1. navigate to /components/jump-links/demo
2. use screenreader to navigate jump-links nav
3. list should be labelled by the slotted heading
1. same as case 1, but at mobile breakpoint
NOTE TO testers: in my testing using VO and FF, the header text was repeated `list STANDARD SECTION standard section 5 items`. Edgium and safari did not repeat, so i suppose that's a UA thing. …

fix(jump-links): apply aria-label to list

---

.changeset/nervous-meals-turn.md
core/pfe-core/package.json

Makes each module from core explicit in the export map.
This enables node-based tools to read the files specified.
See https://github.com/rhdemo/2022-game-app/pull/20#issuecomment-1067527033
- create a fresh project with `npm init -y`
- Set the repo's `type` to `module`.
- Install pfe-core via `npm link`.
- try to import a file from core via the node repl

fix(core): make export map explicit

---

.changeset/blue-emus-draw.md
tools/create-element/package.json

also bump version number to 1.0
-----
See how `create-element` is shipped without js sources? that prevents anyone from actually using it 🤦 
https://unpkg.com/browse/@patternfly/create-element@next/

fix(create): ship js to npm

---

.changeset/fifty-boxes-peel.md
tools/pfe-tools/README.md
tools/pfe-tools/dev-server.ts

- Tries to guess the repo root when run either from `/node_modules` or from within the pfe monorepo
- Adds a `Troubleshooting` section to README to offer guidance to users who's case was not covered by the above

fix(tools): try to get repo root automatically

---

package.json

The @patternfly/create-element tool is not included in the post install scripts which means to run npm run new you need to first run npm run build -w @patternfly/create-elements if you plan to use the new script. This should be updated so that it is handled by the postinstall scripts.
- (#1963)

fix(tools): adding @patternfly/create-element to postinstall scripts

---

.changeset/brave-feet-sing.md
docs/demo/demo.ts
elements/pfe-card/demo/pfe-card.html
elements/pfe-card/package.json
elements/pfe-cta/demo/pfe-cta.html
elements/pfe-cta/package.json
elements/pfe-jump-links/demo/pfe-jump-links.js
package.json

see https://github.com/justinfagnani/html-include-element/pull/21
`<html-include>` dies when a subresource errors.
This PR patches the `HTMLIncludeElement` class at runtime to prevent that, allowing the rest of the HTML partial to load
> Why not patch-package?
- it's dev-only so i'm less worried about code size
- patch-package would become an error if and when above PR is merged and we update
- i'd rather vend this snippet than vend a patch-package diff 🤷

docs: patch html-includes if needed

---

.changeset/tricky-tools-joke.md
tools/create-element/generator/element.ts
tools/create-element/main.ts
tools/pfe-tools/11ty/DocsPage.ts

Running the generator in a monorepo, the user should be prompted for a scope name, and these files should be written
- tsconfig.json
- custom-elements-manifest.config.js
- package.json
Running the generator in a single package repo, the user should not be prompted for a scope name, and those three files should not be written

feat(create): `--monorepo` flag

---

.changeset/fluffy-rockets-swim.md
elements/pfe-card/pfe-card.ts
tools/pfe-tools/demo/demo.css
tools/pfe-tools/demo/demo.ts
tools/pfe-tools/demo/index.njk
tools/pfe-tools/dev-server.ts

Rewrite dev server to use declarative shadow DOM and to be an MPA.
- remove SPA code from demo.ts
- calculate server-side variables in the dev-server
- inject demo markup into a declarative shadow dom template
- inject demo script into the `<head>`
- add declarative shadow DOM polyfill for FF and Safari
- `npm start`
Closes #2008

feat(tools): use declarative shadow DOM for dev server

---

.changeset/calm-items-cover.md
package-lock.json
tools/pfe-tools/11ty/plugins/pfe-assets.cjs
tools/pfe-tools/esbuild.ts
tools/pfe-tools/package.json

Added some new APIs for `@patternfly/pfe-tools/esbuild.js` to facilitate building daughter single-package repos (i.e. RHDS)
`singleFileBuild` now scans `node_modules` for installed
`@patternfly/pfe-*` packages (except `core`, `tools`, `sass`, and
`styles`) and generates an entrypoint file for them.
Users can alternatively pass `componentsEntryPointsContent`, which is
the string contents of a javascript module that exports the desired
components.
These changes make using `singleFileBuild` more useful and ergonomic for
daughter repositories (e.g. RHDS)
1. `npm run build` <- verify that the minified bundle is good by inspecting the built docs site (can verify this in the deploy preview)
2. patch this version into RHDS (on footer branch) and verify that the 11ty site builds and that the …

feat(tools): single file build entrypoints

---

.changeset/pfe-modal-pfv4-feats.md
.changeset/pfe-modal-pfv4.md
.changeset/pink-news-fail.md
docs/main.css
elements/pfe-modal/README.md
elements/pfe-modal/demo/demo.css
elements/pfe-modal/demo/pfe-modal.html
elements/pfe-modal/demo/pfe-modal.js
elements/pfe-modal/docs/index.md
elements/pfe-modal/pfe-modal.scss
elements/pfe-modal/pfe-modal.ts
elements/pfe-modal/test/pfe-modal.spec.ts
tools/pfe-tools/demo/demo.css
tools/pfe-tools/demo/index.njk
tools/pfe-tools/esbuild.ts

- deprecate the `width` attribute in favour of `variant`
- implement many `--pf-` css variables
- remove _all_ `--pfe-` css variables
- Load up the deploy preview for this branch
- Load up [PatternFly v4 Modal](https://www.patternfly.org/v4/components/modal/)
- Compare and contrast
- Read over the [docs](https://deploy-preview-2036--patternfly-elements.netlify.app/components/modal/) and see if anything's missing or no longer relevant
This PR is *BREAKING*. It aligns pfe-modal with pfv4. the previously-pfe-specific styles and APIs will be moved over to https://github.com/RedHat-UX/red-hat-design-system/pull/288
So dip into the percy tests to see if anything wild broke

feat(modal): PF1:1

---

.changeset/curly-pears-retire.md
elements/pfe-modal/pfe-modal.ts

- change the type of modal's `returnValue` to string from string | undefined, in line with `HTMLDialogElement`

fix(modal): returnValue type

---

elements/pfe-card/demo/demo.css

- apply grid styles to the demo container in the card demo
1. run the dev server
2. http://localhost:8000/demo/card/
3. Observe a grid layout with gap between cards

docs(card): fix demo layout in dev server

---

netlify.toml

use the --ignore-scripts npm flag when netlify runs `npm install` before running the build commmand
we don't want to use netlify's cache because its non-deterministic
so we ignore scripts and don't actually install anything
defering instead to the build command to run npm ci

chore: fix netlify command

---

.github/workflows/preview.yml

Build netlify DPs in github actions
along with this, we disabled deploy previews in the netlify web ui
Also [generated](https://app.netlify.com/user/applications/personal) and set a repo secret called `NETLIFY_AUTH_TOKEN` and copied the [site id](https://app.netlify.com/sites/patternfly-elements/settings/general#site-information) into `NETLIFY_SITE_ID`

chore: add manual netlify builds

---

docs/framework-integration/react.md
docs/framework-integration/vue.md
docs/get-started/index.md
docs/index.md
docs/quick-start/index.md

Advise site visitors to install the `@next` npm dist tag.
See https://github.com/patternfly/patternfly-elements/discussions/2071#discussioncomment-3265153

docs: point to next dist tag

---

.changeset/tender-waves-bow.md
tools/pfe-tools/package.json

- add dev server's web fonts to the npm tarball
In keeping with the theme from #2081 and #2080, i'm planning to merge this small change w/o review

fix(tools): include devserver webfonts

---

.changeset/green-jobs-guess.md
tools/pfe-tools/dev-server.ts

- remove `.ts` files from the default `watchFiles` dev server config, as this somehow prevented wds from serving the updated content

fix(tools): serve changes to ts sources

---

elements/pfe-markdown/README.md
elements/pfe-markdown/pfe-markdown.ts

Changing the link to marked.js to now link to the homepage.  Previous page 404s now. 
https://deploy-preview-2100--patternfly-elements.netlify.app/components/markdown/

docs(markdown): Updating docs page link to marked.js

---

elements/pfe-datetime/demo/pfe-datetime.html
elements/pfe-datetime/docs/pfe-datetime.md

Link to the stylesheet is broken for datetime. Script tag brings in < tag when spaces are put between lines so I went ahead and removed those. 
https://deploy-preview-2101--patternfly-elements.netlify.app/components/datetime/

docs(datetime): fixing href & script tags in datetime docs

---

.changeset/cool-coats-press.md
.changeset/mean-points-drop.md
elements/pfe-autocomplete/package.json
elements/pfe-button/tsconfig.json
elements/pfe-icon/builtin-icon-sets.ts
package-lock.json
tools/eslint-config/package.json
tools/pfe-tools/package.json

Add pfe-button as a dependency to pfe-autocomplete
Closes #2102

chore(autocomplete): add missing dependency

---

.changeset/chatty-cherries-rush.md
tools/pfe-tools/11ty/DocsPage.ts
tools/pfe-tools/11ty/plugins/custom-elements-manifest.cjs
tools/pfe-tools/11ty/plugins/types.ts
tools/pfe-tools/README.md
tools/pfe-tools/config.ts
tools/pfe-tools/custom-elements-manifest.ts
tools/pfe-tools/custom-elements-manifest/demos.ts
tools/pfe-tools/custom-elements-manifest/lib/Manifest.ts
tools/pfe-tools/dev-server.ts

Adds an optional unified config file for custom elements manifest, dev server, and docs pages
Create a `.pfe.config.json` file at the root of your project to customize the pfe tools builds.
The default values are:
```json
{
"tagPrefix": "pfe",
"demoURLPrefix": "https://patternflyelements.org/",
"sourceControlURLPrefix": "https://github.com/patternfly/patternfly-elements/tree/main/",
"aliases": {},
"site": {
"title": "PatternFly Elements",
"description": "PatternFly Elements: A set of community-created web components based on PatternFly design.",
"favicon": "/brand/logo/svg/pfe-icon-blue.svg",
"logoUrl": "/brand/logo/svg/pfe-icon-white-shaded.svg",
"stylesheets": []
}
}
```
See `@patternfly/pfe-tools/config.ts` for more information.
This file is consulted when generating
- custom elements …

feat(tools): config file

---

.changeset/eighty-cheetahs-join.md
.changeset/eleven-toys-unite.md
core/pfe-core/controllers/color-context.ts
core/pfe-core/decorators/color-context.ts
elements/pfe-accordion/pfe-accordion-header.ts
elements/pfe-accordion/pfe-accordion.ts
elements/pfe-autocomplete/package.json
elements/pfe-autocomplete/pfe-autocomplete.ts
elements/pfe-autocomplete/pfe-search-droplist.ts
elements/pfe-clipboard/pfe-clipboard.ts
elements/pfe-clipboard/test/pfe-clipboard.spec.ts
elements/pfe-dropdown/package.json
elements/pfe-dropdown/test/pfe-dropdown.spec.ts
elements/pfe-health-index/package.json
elements/pfe-health-index/test/pfe-health-index.spec.ts
elements/pfe-icon/pfe-icon.ts
elements/pfe-jump-links/pfe-jump-links-nav.ts
elements/pfe-jump-links/test/pfe-jump-links.spec.ts
elements/pfe-tooltip/BaseTooltip.ts
tools/pfe-tools/dev-server.ts
web-dev-server.config.js
web-test-runner.config.js

- update the typescript target in dev server config. this allows top-level await and other features

fix(tools): update dev server ts target

---

elements/pfe-label/package.json

1. Added `files` block to `package.json` with file type exclusions.
```json
"files": [
"!*.ts",
"custom-elements.json",
"**/*.LEGAL.txt",
"**/*.css",
"**/*.d.ts",
"**/*.js",
"**/*.js.map",
"!custom-elements-manifest.config.js",
"!demo/*",
"!docs/*",
"!test/*"
],
```
Not testable until deployed to npm.

chore(label): exclude certain files from npm package

---

.changeset/calm-trains-tie.md
tools/pfe-tools/dev-server.ts

Removed esbuild target configuration relying on tsconfig.json for configuration options.
1. Checkout branch
2. Run `npm start`
3. Validate working components
4. Closes #2166 
Reference: https://github.com/RedHat-UX/red-hat-design-system/issues/568

fix(tools):  remove esbuild target configuration

---

.gitignore
netlify.toml

Attempting to fix the Netlify build by following the guidance here:
https://github.com/netlify/build/issues/1640
The issue with the local plugin is that the dependencies are not installed. The additional plugin should fix the issue.

chore: fix netlify build by adding plugin-local-install-core

---

netlify.toml
package-lock.json
package.json

Previous attempts to fix the netlify build all failed. At this point the best thing to do is remove the visual-regression workflow trigger (which we're anyways not really using) so that we can deploy from main.

chore: remove netlify visual regression workflow

---

.changeset/odd-lamps-rescue.md
elements/pfe-accordion/BaseAccordion.ts
elements/pfe-accordion/BaseAccordionHeader.ts
elements/pfe-jump-links/demo/pfe-jump-links.js

Updating the icon in BaseAccordionHeader as it was built for the previous pfe-icon spec and this will follow the new one with a customizable set attribute. 
- #2182
- Changed the default icon string that is used in BaseAccordionHeader along with adding an icon-set attribute to the component for compability with pfe-icon.
- Updated the pfe-jump-links.js because it is throwing an error currently in the console log that I noticed while testing.

fix(accordion): :bug: updating the icon in BaseAccordionHeader

---

core/pfe-core/functions/isElementInView.ts
elements/pfe-tabs/BaseTab.scss
elements/pfe-tabs/BaseTab.ts
elements/pfe-tabs/BaseTabPanel.scss
elements/pfe-tabs/BaseTabPanel.ts
elements/pfe-tabs/BaseTabs.scss
elements/pfe-tabs/BaseTabs.ts
elements/pfe-tabs/demo/pfe-tabs.html
elements/pfe-tabs/pfe-tab-panel.scss
elements/pfe-tabs/pfe-tab.scss
elements/pfe-tabs/pfe-tabs.scss
elements/pfe-tabs/pfe-tabs.ts
elements/pfe-tabs/test/pfe-tabs.spec.ts

- use ElementInternals
- many refactors (see commit messages)
- some perf improvements (i.e. use a single listener on window)
- rename `tab-expand` to `expand`
- move all the pf css to the pfe-*.scss files
- add attrs to customize the aria-label for scroll buttons
- remove some dependencies
- use pfe-icon

fix(tabs): many refactors

---

elements/pfe-icon/tsconfig.json

add icon deps to ts ref. fixes [build errors](https://github.com/patternfly/patternfly-elements/actions/runs/3295121081/jobs/5433338016) and unblocks release

fix(icon): add dependencies to ts references

---

.changeset/smooth-chefs-listen.md
elements/pfe-accordion/BaseAccordion.scss
elements/pfe-accordion/BaseAccordionHeader.scss
elements/pfe-accordion/BaseAccordionPanel.scss
elements/pfe-accordion/package.json
elements/pfe-accordion/pfe-accordion-header.scss
elements/pfe-accordion/pfe-accordion-panel.scss
elements/pfe-accordion/pfe-accordion.scss

- Updating the accordion styles to match the format where the variable specific styles go into pfe-accordion.scss instead of BaseAccordion.scss
- Updating exports for package.json
- Address sidebar gap when bordered style is used
- #2195

[pfe-accordion]: Updating stylesheets, package.json exports, and gap 

---

.changeset/breezy-steaks-melt.md
.github/workflows/tests.yml
elements/pfe-icon/demo/pfe-icon.js
elements/pfe-icon/pfe-icon.ts
elements/pfe-icon/tsconfig.json
elements/pfe-label/pfe-label.ts
elements/pfe-label/test/pfe-label.spec.ts

- Fix typescript errors in pfe-icon
- Fix some runtime errors in pfe-label (would have been `static styles = [[basestyle], style]`)
- Add the release dry run step to PR checks

chore: build and release fixes

---

.changeset/breezy-melons-sell.md
docs/_includes/_head.njk
package-lock.json
tools/pfe-tools/11ty/plugins/pfe-assets.cjs
tools/pfe-tools/package.json

- update the element internals polyfill to a version which fixes click-on-label 
- copy the polyfill to the web root when building 11ty
- load the polyfill on all docs pages
fixes #2214 
load /components/switch in safari
I'm loading the polyfill on all pages, this could be more carefully scoped by examining the page data in _head.njk, but that seemed excessively precious to me.

fix(tools): update element internals polyfill

---

.changeset/giant-spies-love.md
elements/pfe-switch/BaseSwitch.scss
elements/pfe-switch/BaseSwitch.ts
elements/pfe-switch/README.md

Fixes issue in Firefox where when `pfe-switch` is disabled, the switch can still be toggled. This PR exits the `#toggle` method if `pfe-switch` is disabled.
Fixes #2215.
- #2215
- Go to https://deploy-preview-2221--patternfly-elements.netlify.app/components/switch/demo/#disabled in Firefox
- Try to click on the switch to make it toggle

fix(switch): making sure toggle isn't called when switch is disabled

---

elements/pfe-switch/demo/pfe-switch.html
elements/pfe-switch/docs/pfe-switch.md

Removes duplicate `disabled` id from docs and demo pages.
Fixes #2224

docs(switch): fixing issue with duplicate ids on demo and docs

---

elements/pfe-switch/package.json

Noticed an issue while working with the new pfe-switch where the published package included the .ts and .scss files.  Added those to ignore from package.json.  
Example on unpkg: https://unpkg.com/browse/@patternfly/pfe-switch@2.0.0-next.0/

fix(switch): adding repo and file list to package.json

---

.changeset/proud-wombats-dress.md
elements/pfe-badge/BaseBadge.ts
elements/pfe-badge/pfe-badge.ts

Make `state` property on `BaseBadge` abstract. Blocks https://github.com/RedHat-UX/red-hat-design-system/pull/599

fix(badge)!: make state abstract

---

docs/main.css
package.json

1. Changed the engines included in the package.json since we are currently on node v18.12.1
2. Updated the styles for the `.band` class as they weren't showing up with the correct width for me in Firefox or Chrome.  Open to suggestions on this one as I'm not sure if it's necessary to keep the code or to have it only apply for screens >= 768px.

docs: band padding & node engine increment in package.json 

---

.changeset/little-timers-repeat.md
.changeset/modern-readers-joke.md
.changeset/shy-knives-walk.md
.changeset/spicy-pans-draw.md
core/pfe-core/controllers/internals-controller.ts
elements/pfe-button/BaseButton.ts
elements/pfe-button/demo/form-control.html
elements/pfe-button/demo/form-control.js
elements/pfe-button/test/pfe-button.spec.ts
package-lock.json
tools/pfe-tools/dev-server/index.html
tools/pfe-tools/package.json

- proxy `role` and `aria*` props in `ElementInternals` to `InternalsController`
- wrap the host's `form*Callback` methods in `InternalsController`
- add `formDisabled: boolean` to `InternalsController`
- disable BaseButton if it's disabled either by attr or by form, without requiring the reflected attr when form is disabled.
Check out button's `form controls` demo and make sure everything's kosher there

feat(core): internals controller improvements

---

.changeset/short-donuts-remain.md
tools/create-element/templates/element/custom-elements-manifest.config.js
tools/create-element/templates/element/demo/demo.css
tools/create-element/templates/element/demo/element.html
tools/create-element/templates/element/demo/element.js
tools/create-element/templates/element/element.ts

- remove `@pfelement` decorator from create-element templates
- remove static version string from same
- update demo css and js
closes https://github.com/RedHat-UX/red-hat-design-system/issues/577

fix(create-element): remove pfelement decorator

---

.changeset/fuzzy-plants-peel.md
elements/pfe-tabs/BaseTab.ts
elements/pfe-tabs/BaseTabPanel.ts
elements/pfe-tabs/BaseTabs.ts
elements/pfe-tabs/test/pfe-tabs.spec.ts

- Fixed focus on keyboard navigation, await tabindex update before applying `.focus()` on selected tab.
- Fixed incorrect placement of tabindex on the container of tab and not the button
See [deploy preview demo](https://deploy-preview-2301--patternfly-elements.netlify.app/components/tabs/demo/).
Check for accessibility of keyboard navigation and correctness of set focus.

fix(tabs): focus on keyboard navigation

---

core/pfe-core/controllers/roving-tabindex-controller.ts
core/pfe-core/package.json
elements/pfe-jump-links/pfe-jump-links-item.ts
elements/pfe-jump-links/pfe-jump-links.ts
elements/pfe-jump-links/test/pfe-jump-links.spec.ts

##What I Did
- Added `roving-tabindex-controller.js` to `pfe-core`
- Used the controller with `pfe-jump-links`

fix(jump-links): roving tab-index

---

.changeset/little-dolls-draw.md
elements/pfe-tabs/BaseTab.ts

- Removed imperative modification of the `tabindex` attribute

refactor(tabs): remove imperative modification

---

package-lock.json
package.json

- update wireit, allowing script dependencies that aren't defined in `"scripts"`
- remove intermediate scripts from `"scripts"`

chore: remove extraneous script entrypoints

---

docs/_data/importMap.cjs
docs/_plugins/pfe-assets.cjs
scripts/bundle.js

- Added passthroughcopy for `pfe.min.js`
- Added import map for `pfe-core` controllers, functions and decorators

docs: passthrough copy and import maps for pfe.min.js

---

docs/main.css

There is a bug in that the  docs site footer should shift over when sidebar menu is open, but the CSS property is incorrect. 
Corrected the CSS prop from `translate` to  `transform: translate();`
1. Go here
2. Do this
1. Go here
2. Do this

docs: footer translate

---

.changeset/curvy-windows-poke.md
.changeset/itchy-roses-vanish.md
tools/pfe-tools/typescript/transformers/css-imports.cjs
tsconfig.settings.json

1. Added `minify` option to css-imports typescript transform and enabled it in build config
2. Fixed `inline` option of css-imports transformer to allow ts sources to import multiple css sheets
Say you had these files:
- a.css
```css
a { color: var(--a); }
```
- b.css
```css
b { color: var(--b); }
```
- m.ts
```ts
import a from './a.css';
import b from './b.css';
export {a, b};
```
Try building using ttsc with this config:
```json
{
"compilerOptions": {
"module": "es2020",
"moduleResolution": "Node",
"strict": true,
"target": "es2020",
"plugins": [
{
"transform": "@patternfly/pfe-tools/typescript/transformers/css-imports.cjs",
"inline": true,
"minify": true
}
]
}
}
```
Before: 
```js
import { css } from "lit";
const a = css `a { color: var(--a); }`;
import { css } from "lit";
const b = …
```

feat(tools): add minify option to ts css-imports

---

docs/_includes/_foot.njk
docs/home.css

Previously we had updated the copyright date in the footer to 2022 - {{ currentYear }}, this needs to be updated to 2018 - {{ currentYear }}

fix(docs): Updating footer copyright date to 2018-2023

---

.changeset/core-overflow-controller.md
.changeset/eighty-colts-study.md
.changeset/tabs-update-overflow.md
core/pfe-core/controllers/overflow-controller.ts
core/pfe-core/functions/isElementInView.ts
docs/components/demos.html
elements/pf-tabs/BaseTabs.ts
elements/pf-tabs/demo/pf-tabs.js
elements/pf-tabs/pf-tabs.css

1.  Added `OverflowController` which when added to a container and given a child array of elements checks to see if those elements exceed the bounds of the container. 
2. Integrated overflow controller into `BaseTabs`.
1. View [deploy preview tabs demo](https://deploy-preview-2375--patternfly-elements.netlify.app/components/tabs/demo/)
2. View at varying browser sizes mobile -> desktop
1. Look for any issues around overflow such next and previous buttons not properly displaying the disabled state when tabs are overflowed left or right.
2. Assuming we will want to move the changeset back into the reorganized condensed format.

feat(core): add overflow controller

---

.changeset/famous-cars-dress.md
tools/pfe-tools/11ty/plugins/custom-elements-manifest.cjs
tools/pfe-tools/config.ts

Closes #2376
1. added an `elementsDir` option to pfe.config.json
2. use that to compute demo paths, or default to `elements`
1. copy the contents of custom-elements-manifest.cjs to `node_modules/@patternfly/pfe-tools/11ty/plugins/custom-elements-manifest.cjs`
2. make sure both the dev server and the 11ty site demos work as expected

fix(tools): calculate path to demo files

---

.changeset/forty-lamps-fold.md
elements/pf-clipboard-copy/pf-clipboard-copy.css

1. Fixed inline variant styles to `display: inline-flex` to prevent wrapping
Closes #2433 
1. Check the [deploy preview demo](https://deploy-preview-2434--patternfly-elements.netlify.app/components/clipboard-copy/), and ensure inline variant styles are correct

fix(clipboard-copy): inline styles

---

.changeset/wild-falcons-do.md
elements/pf-accordion/BaseAccordionPanel.css

1.  Added `overflow:hidden` to the panel so that the accent will span the whole height of the div in cases where the slotted content has margins / padding.

fix(accordion): large panel accent not covering whole side panel 

---

.changeset/bright-papayas-crash.md
.changeset/pf-accordion-header-tags.md
.changeset/pf-accordion-headers.md
elements/pf-accordion/BaseAccordionHeader.ts
elements/pf-accordion/demo/pf-accordion.html

1. Added an `anonymous` slot checker in the `pf-accordion-header` component. 
- This checks for whether an `anonymous` slot has been passed in for the header
- DOES NOT have an `anonymous` slot = we add the header tag to the shadow dom
- DOES have an `anonymous` slot = we DO NOT add the header tag to the shadow dom
2. We have / had an issue with the `heading-text` attribute not showing correctly in the header, this has been fixed
3. Adding a demo to show the attributes being used instead of the `anonymous` slot
1. [DP](https://deploy-preview-2435--patternfly-elements.netlify.app/components/accordion/demo/)
2. Open the developer console and inspect the accordion demos
3. Verify that the accordion headers with slotted in content do not have nested header tags in the shadow dom
4. Verify …

fix(accordion): fixing header tag, fixing heading text attribute  

---

.pfe.config.json
docs/_includes/_nav.njk
docs/_includes/layout-basic.njk
docs/_includes/layout-blog-index.njk
docs/_includes/layout-blog.njk
docs/components/components.md
docs/main.css

1. Fixed blog layout
2. Fixed regression in component headers style due to changes with addition of `renderTitleInOverview` https://github.com/patternfly/patternfly-elements/pull/2444
3. Added a `.pfe.config.json` to include the new `renderTitleInOverview: false` setting.
Closes #2451
1. [Check out the blog](https://deploy-preview-2459--patternfly-elements.netlify.app/blog/)
2. [Check out component headers](https://deploy-preview-2459--patternfly-elements.netlify.app/components/tabs/)

docs: fix blog layout and component headers

---

docs/home.css

Closes #2453
1. Fixed get started CTA color on hover 
1. Open the docs link and hover over the get started CTA (also set focus + hover in dev tools) and verify the text color is white.
1. I don't think we're using `pfe-cta` in the docs anymore? Should we remove those custom variable overrides?

docs: set text color to white on hover

---

.changeset/cuddly-scissors-reply.md
tools/pfe-tools/11ty/DocsPage.ts
tools/pfe-tools/custom-elements-manifest/lib/Manifest.ts

1. Removed special characters from component slugs.
2. Used [slugify](https://github.com/simov/slugify#options) `strict` mode and `lower` options to ensure slugs are lowercase and do not contain special characters.
1. Double-check all demos and docs pages that no URLs are broken in Deploy Preview
2. Add an alias to `.pfe.config.json`. Fire up the local server and docs site, again ensure no URLs are broken
```json
{
"aliases": {
"pf-tabs": "Tabs (Special Snowflake)"
}
...
}
```

fix(tools): remove special characters from slugs

---

.changeset/stale-boxes-watch.md
elements/pf-accordion/BaseAccordion.ts
elements/pf-accordion/pf-accordion.ts
elements/pf-accordion/test/pf-accordion.spec.ts

1. Removed auto focus on expanded for the accordion header
Closes #2454 
This is so that if you have an expanded accordion down the page it doesn't automatically scroll the user down to the accordion.
1. Check out the DP and verify the accordion docs page doesn't auto focus on the expanded header in the demo docs

fix(accordion): removing auto focus on expanded in the header

---

.changeset/tools-site-subpath.md
.pfe.config.json
elements/custom-elements-manifest.config.js
tools/pfe-tools/11ty/plugins/custom-elements-manifest.cjs
tools/pfe-tools/config.ts
tools/pfe-tools/custom-elements-manifest/config.ts
tools/pfe-tools/custom-elements-manifest/demos.ts
tools/pfe-tools/custom-elements-manifest/lib/Manifest.ts

1. add `site.subpath` to `.pfe.config.json` to rhds can override it with `/elements`
2. thereby fix cem demo references
1. copy to rhds node_modules and run the docs build
1. yolo
2. I specifically avoided mucking about with the dev server config here, because i'm scared to break stuff :sweat_smile:

feat(tools): site.componentSubpath config

---

docs/main.css

1. Added styles for `htmlexample` shortcode (details/summary) that mimics [Patternfly Expandable section](https://www.patternfly.org/v4/components/expandable-section)

docs: add html example styles

---

eleventy.config.cjs

1. Corrected sorting type spelling
Closes #2465.
1. Run the docs site locally and verify that the nav items are ordered alphabetically.

fix: order name typo

---

.changeset/perfect-dragons-double.md
elements/pf-tabs/BaseTab.ts
elements/pf-tabs/BaseTabPanel.ts
elements/pf-tabs/BaseTabs.ts

1. Added a check in the tabExpand event handler to check the event.tab object ensuring it is not the same as the tabindex activeItem before updating.  
2. Override `focus()` on tab applying focus to the shadowroot `button`.
Closes #2484 
Changes here need to be tested upstream in RHDS.  You will need to copy  or `npm link` the compiled files into RHDS to test.
1. Ensure that all arrow keys, page up, page down, and click events continue work in all browsers under different network conditions and load using the [deploy preview](https://deploy-preview-2485--patternfly-elements.netlify.app/components/tabs/demo/)
3. Check to make sure focus styles are applied correctly.

fix(tabs): fix focus on keyboard navigation for safari

---

.changeset/two-pugs-add.md
core/pfe-core/controllers/overflow-controller.ts

1. Refactored scroll calculation for scrollLeft and scrollRight in overflow controller
2. Added smooth scroll behavior
3. Refactored showScrollButtons calculation to include scroll button width in hiding and showing the buttons.
1. View [Deploy preview ](https://deploy-preview-2486--patternfly-elements.netlify.app/components/tabs/demo/)
1. Ensure that this works across all browsers and screen sizes.  Please use Browserstack and try a variety of devices

fix(core): overflow controller scroll on small screens

---

.changeset/short-tools-lay.md
elements/pf-timestamp/demo/pf-timestamp.html
elements/pf-timestamp/pf-timestamp.ts
elements/pf-timestamp/test/pf-timestamp.spec.ts

1. Updated the relative time calculation to use [Intl.RelativeTimeFormatUnit](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat)
2. Issue: https://github.com/patternfly/patternfly-elements/issues/2503
1. Check that the various timespan options are unaffected
1. This will change the text for future times from being "XX [units] until" to "in XX [units]"
3. Past times should still remain "XX [units] ago"

refactor(timestamp): use Intl.RelativeTimeFormatUnit

---

.changeset/fuzzy-walls-walk.md
tools/pfe-tools/config.ts
tools/pfe-tools/dev-server/config.ts

1. Corrects aliased elements redirects in dev-server
1. Dev Server locally add the configuration from the `.pfe.config.json` below:
Given a `.pfe.conf.json`  with the following contents:
```
{
"renderTitleInOverview": false,
"aliases": {
"pf-modal": "Marvelous Modals",
"pf-tabs": "Terrific Tabs",
"pf-clipboard-copy": "Making Copies",
"pf-tile": "Tantalizing Tiles"
}
}
```
A request  to pf-modals demo.css would produce a URL in the dev-server as: 
http://localhost:8000/components/magnificent-modal/demo/demo.css
Using deslugify we take the `magnificient-modal` slug and check for an alias and return it, If there is no alias we simply return the original path requested ensuring it has the correct tag prefix.
http://localhost:8000/components/magnificent-modal/demo/demo.css
Redirects to => …

fix(tools): dev server aliased element redirects

---

.changeset/few-hotels-punch.md
elements/pf-tabs/pf-tab.css

1. Fixed style regression on tabs when a slotted icon is not present
1.  View [Deploy preview](https://deploy-preview-2519--patternfly-elements.netlify.app/components/tabs/)
1.  Tabs without icons should not have extra space, the icon slot should be hidden

fix(tabs): style regression when no icon is present

---

.changeset/generator-instance-check.md
.changeset/tabs-imperative-instance.md
elements/pf-accordion/test/pf-accordion.spec.ts
elements/pf-avatar/test/pf-avatar.spec.ts
elements/pf-badge/test/pf-badge.spec.ts
elements/pf-button/test/pf-button.spec.ts
elements/pf-card/test/pf-card.spec.ts
elements/pf-clipboard-copy/test/pf-clipboard-copy.spec.ts
elements/pf-code-block/test/pf-code-block.spec.ts
elements/pf-icon/test/pf-icon.spec.ts
elements/pf-jump-links/test/pf-jump-links.spec.ts
elements/pf-label/test/pf-label.spec.ts
elements/pf-modal/test/pf-modal.spec.ts
elements/pf-panel/test/pf-panel.spec.ts
elements/pf-popover/test/pf-popover.spec.ts
elements/pf-progress-stepper/test/pf-progress-stepper.spec.ts
elements/pf-spinner/test/pf-spinner.spec.ts
elements/pf-switch/test/pf-switch.spec.ts
elements/pf-tabs/BaseTabPanel.ts
elements/pf-tabs/test/pf-tabs.spec.ts
elements/pf-tile/test/pf-tile.spec.ts
elements/pf-timestamp/test/pf-timestamp.spec.ts
elements/pf-tooltip/test/pf-tooltip.spec.ts
tools/create-element/templates/element/test/element.spec.ts

1. defer creation of `hidden` attribute until connectedCallback
2. add regression tests for `document.createElement('pf-*')`
3. add that test to the generator for future elements
1. run the tests, try tabs with tabs panel in a react app
1. Fixes #2491

fix(tabs): imperative instantiation of tabs-panel

---

.changeset/neat-colts-jam.md
elements/pf-accordion/BaseAccordion.ts
elements/pf-accordion/BaseAccordionHeader.ts
elements/pf-accordion/test/pf-accordion.spec.ts

#2537 
1.  Added an index check to the `collapse` function so that if the element that called the `change` event is not an `accordion-*` element it will not cause the panel to close.

fix(accordion): panel checkbox collapsing panel on check

---

.changeset/late-actors-give.md
elements/pf-accordion/BaseAccordion.ts
elements/pf-accordion/test/pf-accordion.spec.ts

1. Determined that #2496 was an issue with `BaseAccordion`'s use of `roving-tabindex-controller` rather than the controller itself.
2. Modified `BaseAccordion`'s `get #activeHeader` so that if no active header is found, the active header is returned as `undefined`.
3. Fixed issues with testing. (When focus is in the accordion panel and tab is pressed, focus should go to the body.)
1. Go to the [Fixed Panel demo in DP](https://deploy-preview-2555--patternfly-elements.netlify.app/components/accordion/demo/)
2. Expand Item three.
4. Tab to Focus on me!
5. Use arrow keys.
6. The focus **_should not_** change.

bug: accordion and roving tabindex controller

---

docs/main.css

1. Removed skip link animation so link doesn't animate at page load
Closes #2553 
1.  View [Deploy Preview](https://deploy-preview-2554--patternfly-elements.netlify.app/)
1.  If you view patternflyelements.org before this PR is merged you'll notice on page loads the skip link will animate that was unintended.  This PR removes the animation all together as it really isn't needed for the links main purpose.

docs: remove skip link animation

---

.changeset/pf-card-heading-specificity.md
elements/pf-card/BaseCard.css
elements/pf-card/pf-card.css

1. make slotted styles in card `!important`
1. try with this page:
```html
<style>
:is(h1, h2, h3, h4, h5, h6) {
font-family: var(--rh-font-family-heading);
margin-block: var(--rh-space-xl);
line-height: 1;
}
</style>
<pf-card>
<h3 slot=header>Haha broke your styles!</h3>
</pf-card>
```
1. `!important` isn't great but these are design system tokens so I feel it's justified. You could argue that the margin values should not be important, but I think in this case they're specified so it's ok.

fix(card): make slotted styles !important

---

.changeset/downlevel-es2020.md
tsconfig.settings.json

fixes #1157
1. downlevel element output to es2020
1. compile, ripgrep for `static ?\{` in js files

fix: downlevel output files to es2020

---

.changeset/new-maps-lick.md
elements/pf-progress/docs/pf-progress.md
elements/pf-progress/pf-progress.css

1.  Updated `success`, `warning`, and `danger` variant css to fix variant background color.

fix(progress): fixing css selectors for variants

---

.changeset/rich-kangaroos-brake.md

1.  Updating the changeset for the release to have the attribute `description` instead of `title` as title does not exist on pf-progress elements.

[progress]: updating changeset attr from title to description

---

.changeset/pf-text-input-placeholder.md
elements/pf-text-input/pf-text-input.ts

Closes #2594
1. add `placeholder` attr/prop pair which forwards to input.
1. Load Deploy preview input demo, set placeholder DOM property, add placeholder attribute
https://deploy-preview-2595--patternfly-elements.netlify.app/components/text-input/demo/
```js
document.querySelector('pf-text-input').placeholder = "world"
document.querySelector('pf-text-input').setAttribute('placeholder', 'hello')
```
1. This api doesn't exist on the react component, but makes sense for the custom element.
3. please check that styles are congruent with upstream

feat(text-input): placeholder

---

.changeset/accordion-no-animate.md
docs/main.css
elements/pf-accordion/BaseAccordion.css
elements/pf-accordion/BaseAccordion.ts
elements/pf-accordion/BaseAccordionPanel.css

fixes #2597
1. remove animations from accordion
1. although this change removes things, i believe all the removed elements are private, so this is a patch. Please confirm

fix(accordion): remove animation

---

elements/pf-accordion/BaseAccordion.ts
elements/pf-accordion/pf-accordion.ts

#2642 
1.  Remove `static styles` from base accordion, removed import for pf-accordion.
The pipeline should be fixed with this commit.  Base accordion does not contain any style files

fix(accordion): removing base accordion styles

---

.changeset/input-submit.md
elements/pf-text-input/demo/form-submission.html
elements/pf-text-input/pf-text-input.ts

feat(text-input): form submission

---

.changeset/internals-controller-computed-label-text.md
.changeset/internals-controller-props.md
.changeset/pf-text-area.md
core/pfe-core/controllers/internals-controller.ts
elements/package.json
elements/pf-accordion/BaseAccordion.ts
elements/pf-accordion/pf-accordion.ts
elements/pf-button/BaseButton.ts
elements/pf-text-area/README.md
elements/pf-text-area/demo/auto-resizing.html
elements/pf-text-area/demo/disabled.html
elements/pf-text-area/demo/horizontally-resizable.html
elements/pf-text-area/demo/invalid.html
elements/pf-text-area/demo/pf-text-area.html
elements/pf-text-area/demo/readonly.html
elements/pf-text-area/demo/validated.html
elements/pf-text-area/demo/vertically-resizable.html
elements/pf-text-area/docs/pf-text-area.md
elements/pf-text-area/pf-text-area.css
elements/pf-text-area/pf-text-area.ts
elements/pf-text-area/test/pf-text-area.e2e.ts
elements/pf-text-area/test/pf-text-area.spec.ts
elements/pf-text-input/pf-text-input.ts

1. add features to InternalsController
2. move code from PfTextInput to InternalsController
3. add pf-text-area
1. extensive usability testing is required
2. re-test pf-text-area which is also updated here
1. depending on which PR is merged first, this also could impact pf-checkbox, radio, switch - anything with element internals
2. i'm not 100% clear on the polyfill story, so try in webkit and firefox as well

feat(text-area): add pf-text-area

---

elements/pf-background-image/demo/sibling-content.html
elements/pf-chip/pf-chip.css
elements/pf-dropdown/pf-dropdown.css
elements/pf-select/pf-listbox.css
elements/pf-select/pf-option-group.css

1.  Remove color theme token, replace with PFv4 tokens in a best guess.  
Closes #2660
1.
1.  If I could find one that seemed to fit the use case I swapped it otherwise used the global version.   Not ideal but don't think our use cases always match perfect.  PTAL, correct my mistakes were plausible.

fix: remove color theme token, replace with PFv4 tokens

---

elements/pf-tabs/demo/active-tab-disabled.html
elements/pf-tabs/demo/active-tab-is-disabled.html
elements/pf-tabs/demo/box.html
elements/pf-tabs/demo/dynamic-tabs.html
elements/pf-tabs/demo/filled-with-icons.html
elements/pf-tabs/demo/filled.html
elements/pf-tabs/demo/icons-and-text.html
elements/pf-tabs/demo/inset.html
elements/pf-tabs/demo/manual-activation.html
elements/pf-tabs/demo/nested.html
elements/pf-tabs/demo/overflow.html
elements/pf-tabs/demo/pf-tabs.html
elements/pf-tabs/demo/tabs-first-in-markup.html
elements/pf-tabs/demo/vertical.html

1.  Fixed a brain fart typo `scroll-x` should have been `overflow-x`
1.
1.

docs(tabs): fix typo in css rule in demo

---

docs/_data/importMap.cjs
package-lock.json
package.json
scripts/bundle.js
tsconfig.esbuild.json
tsconfig.settings.json

1. unminify the shadow css when bundling
1. on the [DP chip group demo page](https://deploy-preview-2710--patternfly-elements.netlify.app/components/chip/demo/chip-group-with-visible-category-name/), chip close buttons should be vertically centered, as normal. If this PR is broken, they will appear below the vertical center line.

fix: unminify css when bundling

---

elements/pf-button/pf-button.ts

1. Prevented default behavior on spacebar keydown
1. Go to [Button docs on DP](https://deploy-preview-2716--patternfly-elements.netlify.app/components/button/)
2. Press <kbd>Tab</kbd> to navigate to any button.
3. Press spacebar.
4. Browser window scrolls.

fix(button): prevent default behavior for spacebar

---

.changeset/rare-news-drum.md
core/pfe-core/controllers/internals-controller.ts

1. Added `ariaDescription` to `InternalsController`
Closes #2726 
1.
1.

fix(core): add missing `ariaDescription` to InternalsController

---

.changeset/nice-moments-doubt.md
core/pfe-core/controllers/tabs-aria-controller.ts
elements/pf-tabs/pf-tab-panel.ts
elements/pf-tabs/pf-tabs.ts

1. apply role to tab and tab-panel elements directly, via `TabsAriaController`
1. Closes #2692, see lighthouse results there

fix(tabs): roles in sr

---

.changeset/upset-birds-mix.md
elements/pf-clipboard-copy/pf-clipboard-copy.css

Fixes #2741
1. apply negative padding to the button height
1. [check the dp](https://deploy-preview-2761--patternfly-elements.netlify.app/components/clipboard-copy/demo/)

fix(clipboard-copy): copy button height

---

.changeset/rich-sloths-reply.md
tools/pfe-tools/react/generate-wrappers.ts

1. remove extraneous `,` from generated react wrapper modules when there is more than one element exported.
1. run the build on rhds and confirm that `rh-navigation-secondary-dropdown.js` does not include the pattern `/;,$/`
1. See https://github.com/jspm/project/issues/336#issuecomment-2171057720
2. With many thanks to the inimitable @guybedford

fix(tools): react wrapper syntax errors

---

.changeset/healthy-clocks-laugh.md
tools/pfe-tools/react/generate-wrappers.ts

1. remove non-exported ce classes from react wrapper files

fix(tools): don't export react wrapper for non-exported class

---

.changeset/shaky-cats-share.md
tools/create-element/generator/element.ts
tools/create-element/templates/element/demo/demo.css
tools/create-element/templates/element/demo/element.html
tools/create-element/templates/element/demo/element.js

1. update the generator's demo templates, removing the `demo.css` and `${elementName}.js` subresources, and inlining them to the HTML instead.

fix(create-element): inline demo subresources

---

.changeset/slick-bats-brake.md
tools/pfe-tools/package.json
tools/pfe-tools/typescript/transformers/css-imports.cjs
tools/pfe-tools/typescript/transformers/static-version.cjs
tsconfig.settings.json

1. add a typescript transform to a static version property to custom element classes
1. run build
2. check that element `.js` files have a static version property
3. run the dev server
4. `customElements.whenDefined('pf-button').then(PfButton => console.log(PfButton.version));`
5. copy `static-version.cjs` into `@rhds/elements` node_modules, along with the package.json for pfe-tools
6. add `{ "transform": "@patternfly/pfe-tools/typescript/transformers/static-version.cjs" },` to tsconfig.json
7. remove the `static version = '{{version}}'` declarations from element files
8. run the build and dev server, and confirm outputs as above.

feat(tools): ts transform to add static version to elements

---

.changeset/dirty-bears-win.md
.changeset/fresh-shrimps-work.md
elements/package.json
elements/pf-icon/README.md
elements/pf-icon/demo/custom-icon-sets.html
elements/pf-icon/docs/pf-icon.md
elements/pf-icon/pf-icon.ts
elements/pf-icon/test/pf-icon.spec.ts
package-lock.json
package.json

1. remove the `getIconUrl` static method
2. add `resolve` static method
3. change the signature of `addIconSet` static method
4. Remove `defaultIconSet` static field
1.
1.

fix(icon)!: remove getIconUrl for webpack's sake

---

docs/main.mjs

1. Fix missing override for `/v2` path pf-icons
Closes #2792
1.
1.

docs: fix v2 pficon getIconUrl override

---

docs/_data/importMap.cjs
package-lock.json
tools/pfe-tools/dev-server/config.ts
tools/pfe-tools/dev-server/plugins/dev-server-router.ts
tools/pfe-tools/dev-server/plugins/dev-server-templates.ts
tools/pfe-tools/dev-server/plugins/pfe-dev-server.ts
tools/pfe-tools/package.json

1. Fix dev-server not serving lightdom.css files
Closes #2794 
1. Follow instructions in #2794 ensure `lightdom.css` and `lightdom-shim.css` serve.
2. Launch dev server `npm run serve`
1.

fix(tools): correct dev server not serving lightdom.css files

---

.changeset/thin-aliens-smoke.md
.github/workflows/tests.yml
core/pfe-core/controllers/internals-controller.ts

safari detector (predictably) breaks everyone else
1.
1.
1.

fix(core): make internals controller ssrable

---

.changeset/funny-teeth-rhyme.md
tools/pfe-tools/typescript/transformers/css-imports.cjs

1. let the typescript css transforms function import from bare specifier e.g. `@rhds/tokens/css/color-context-consumer.css`;

fix(tools): import css from bare specifiers

---

docs/_data/importMap.cjs

1. resolve lit modules from jsdelivr on the docs site

docs: import map

---

.changeset/fluffy-bananas-remember.md
core/pfe-core/controllers/overflow-controller.ts
elements/pf-tabs/test/pf-tabs.spec.ts

Downstream issue:
>  ❌ <rh-tabs> > on small screen > reversed right to left language overflow actions > previousTab should be disabled
Error: ResizeObserver loop completed with undelivered notifications. (http://localhost:8003/?wtr-session-id=E_xerQsq1EQq2yny1h-Ga:0)
> If you want to prevent these errors, the solution depends on what your intended effect is. If you actually intend to have an infinite loop, you just need to defer the resizing code in your ResizeObserver callback to after the browser repaints. You can put it into a [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestAnimationFrame) callback.
[Documentation Reference](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#observation_errors)
1. Await browser repaint before …

fix(core): overflow controller resize loop

---

.changeset/fresh-donuts-count.md
elements/pf-jump-links/pf-jump-links.css

> Centered and Vertical were being incorrectly rendered due to a parsing issue cause by the missing comma in the CSS vars.  
1. Reformatted CSS block, added [previously missing comma](https://github.com/patternfly/patternfly-elements/blob/366d21d835de41f0be0fdf9bbeb5cf881ba9cbe9/elements/pf-jump-links/pf-jump-links.css#L52) which was throwing off Chrome 129 CSS parser.
Thanks @rmscampos for the report
1. View the Deploy Preview
1.

fix(jump-links): fix missing comma throwing off chrome css parser

---

docs/_data/versions.json
netlify.toml

1.  Deployed `release/v3` branch, deployed to netlify
2. Configured netlify.toml to point at new netlify endpoint for v3 release
3. Added v4 as current release version to version.json
1.  View [Deploy Preview](https://deploy-preview-2875--patternfly-elements.netlify.app/) ensure v3 in dropdown redirects
1.

docs: deploy v3 as netlify redirect

---

.changeset/dull-stingrays-film.md
tools/create-element/package.json
tools/create-element/templates/element/element.ts

Commit c9bd577f3 enabled `isolatedDeclarations`, which introduced these errors in `npm new` generated components:
> TS9008: Method must have an explicit return type annotation with --isolatedDeclarations.
> render() {
>
> TS9017: Only const arrays can be inferred with --isolatedDeclarations.
> static readonly styles = [styles];
Fixes #2872
-----
See #2872. Tested with
```
npm run new  # name it "pf-cool" or anything else
npm start
```

fix(tools): fix type errors in create-element template

---

.changeset/olive-rivers-stick.md
core/pfe-core/controllers/slot-controller.ts

1. make slotcontroller's hasContent/isEmpty consider text nodes
1. patch contents into RHDS, and check that cards with text nodes in default slot but no wrapping element still display their contents
1. see https://stackblitz.com/edit/stackblitz-starters-u2qbnw?file=index.html

fix(core): slotController isEmpty respects text nodes

---

elements/pf-tabs/test/pf-tabs.spec.ts

Added axe tree test for aria-selected state

test(tabs): added axe tree test for aria selected state

---

core/pfe-core/controllers/scroll-spy-controller.ts

1. activate the url hash jump link item on page load
1. copy to rhds node_modules
2. load up the rh-jump-links demos
3. click on a jump link (hash)
4. reload the page
5. BEHOLD: hashed item is active

fix(core): activate scroll spy link on connect

---

.github/workflows/preview.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/visual-regression.yml
package-lock.json
package.json

1 . Updated the wireit dependency to 0.14.12
Ref: https://github.com/google/wireit/issues/1297
1. Does the DP fail with cache issues?
1.

chore: update wireit dep for cache v2 api

---

.changeset/fresh-things-burn.md
core/pfe-core/controllers/slot-controller.ts
core/pfe-core/controllers/test/slot-controller.spec.ts

1. Wait until first update to initialize slot map

fix(core): initialize slotcontroller map after update

---

.github/workflows/commitlint.yml

the pull_request_target event runs in the base context, e.g. the main branch, not in the pr branch
therefore this fails for new elements, because the commitlint script can't find the element name for an element which doesn't exist yet on main
1. remove pull request target event from prlint workflow

chore: update commitlint.yml

---

tools/pfe-tools/package.json

1. adds `PfeDemoPage.js` to `package.json` exports
2. This file is used in RHDS E2E testing and needs to be exported.
3. See https://github.com/RedHat-UX/red-hat-design-system/pull/2473 for more info.
1. View `packapge.json` file from pfe-tools, verify things look okay.
2. Verify if any other files in that directory need to be added to the exports list.
Looks like there are some pfe-search-input commits in here. Feel free to change the base branch if applicable.

fix(tools): add `PfeDemoPage.js` to `package.json` exports

---

.changeset/honest-carrots-shout.md
tools/pfe-tools/custom-elements-manifest/custom-elements-manifest.ts
tools/pfe-tools/package.json

1. restored the custom elements manifest utilities that are not related to the old cem/a analyzer

fix(tools): restore accidentally deleted cem utilities
